<?php
// ReliCheck Studio Registry
// -------------------------------------------------------------------
// Source of truth for which studios exist and their identity. Used by:
//   - Platform Shell welcome (the studio picker tiles)
//   - Studio Template (the identity strip at the top of a studio page)
// Item visibility per studio lives in _studio_items_catalog.php.
//
// To add a new studio: add a key here (slug as the array key), then add
// items that target it in the catalog. The status field drives what shows
// on the welcome picker and what's editable in a given pass.
//   live = published; beta = limited use; demo = read-only sample;
//   dev  = in development (visible to internal users only)

return [
  'survey' => [
    'slug'           => 'survey',
    'kind'           => 'app',
    'name'           => 'Survey Development System',
    'mark'           => '/SIRI.png',
    'description'    => 'Build or bring in a survey, check its development strength, prepare it for launch, collect responses, and evaluate the evidence.',
    'status'         => 'live',
    'status_label'   => 'Live',
    'accent'         => '#e85d3a',
    'accent_deep'    => '#c2492f',
    'accent_soft'    => '#fdeee9',
    'primary_action' => 'Open the development workspace',
    'primary_route'  => '/develop.php?db=1',
    'sample'         => [
      'project' => 'Workplace Equity Survey, 2026',
      'context' => '412 responses',
    ],
    'route'  => '/survey-dev.php',
    'direct' => '/develop.php?db=1&start=choose',
  ],
  'mm' => [
    'slug'           => 'mm',
    'name'           => 'MM Studio',
    'mark'           => '/MM%20Studio.png',
    'description'    => 'Connect qualitative and quantitative evidence, build themes, compare groups, and create mixed-methods displays.',
    'status'         => 'beta',
    'status_label'   => 'Beta',
    'accent'         => '#6d4ad8',
    'accent_deep'    => '#5a37c0',
    'accent_soft'    => '#efeafd',
    'primary_action' => 'Build Joint Display',
    'primary_route'  => '/joint-display.php',
    'sample'         => [
      'project' => 'Belonging & Retention Study',
      'context' => '212 surveys, 18 interviews',
    ],
    'route'  => '/studio-mm.php',
    'direct' => '/mmstudioV4.php',
  ],
  'tia' => [
    'slug'           => 'tia',
    'name'           => 'TIA Studio',
    'mark'           => '/TIA%20Studio.png',
    'description'    => 'Analyze tests, items, rubrics, difficulty, discrimination, and cognitive demand.',
    'status'         => 'dev',
    'status_label'   => 'In development',
    'accent'         => '#0e8a6f',
    'accent_deep'    => '#0b6e58',
    'accent_soft'    => '#e3f5ee',
    'primary_action' => 'Run Item Analysis',
    'primary_route'  => '/item-quality.php',
    'sample'         => [
      'project' => '8th Grade Math Test, 2026',
      'context' => '184 students, 40 items',
    ],
    'route'  => '/studio-tia.php',
    'direct' => '/tia-wizard.php?step=1',
  ],
  '360' => [
    'slug'           => '360',
    'name'           => '360 Studio',
    'mark'           => '/360%20Studio.png',
    'description'    => 'Analyze multi-rater feedback across self, peer, manager, and direct-report perspectives.',
    'status'         => 'demo',
    'status_label'   => 'Demo',
    'accent'         => '#2563eb',
    'accent_deep'    => '#1d4ed8',
    'accent_soft'    => '#e6efff',
    'primary_action' => 'Open Perception Gaps',
    'primary_route'  => '/rater-group-comparison.php',
    'sample'         => [
      'project' => 'Leadership 360, Cohort 4',
      'context' => '12 ratees, 84 raters',
    ],
    'route'  => '/studio-360.php',
    'direct' => '/360-wizard.php?step=1',
  ],
  'descriptive' => [
    'slug'           => 'descriptive',
    'name'           => 'Descriptive Analysis Studio',
    'mark'           => '/Descriptive%20Studio.png',
    'description'    => 'Summarize what is present in your data: frequencies, distributions, group summaries, and item rankings.',
    'status'         => 'beta',
    'status_label'   => 'Beta',
    'accent'         => '#c2271b',
    'accent_deep'    => '#a11f15',
    'accent_soft'    => '#fbe9e7',
    'primary_action' => 'Open Descriptive Analysis',
    'primary_route'  => '/descriptive-analysis-workspace.php',
    'sample'         => [
      'project' => 'Workplace Equity Survey, 2026',
      'context' => '412 responses',
    ],
    'route'  => '/descriptive-analysis-studio.php',
    'direct' => '/descriptive-analysis-workspace.php',
  ],
  'inferential' => [
    'slug'           => 'inferential',
    'name'           => 'Inferential Statistics Studio',
    'mark'           => '/Inferential%20Studio.png',
    'description'    => 'Test what your data can support: comparisons, relationships, regression, effect sizes, and assumptions.',
    'status'         => 'beta',
    'status_label'   => 'Beta',
    'accent'         => '#c79114',
    'accent_deep'    => '#a87a0e',
    'accent_soft'    => '#fbf2dc',
    'primary_action' => 'Open Inferential Statistics',
    'primary_route'  => '/inferential-statistics-workspace.php',
    'sample'         => [
      'project' => 'Workplace Equity Survey, 2026',
      'context' => '412 responses',
    ],
    'route'  => '/inferential-statistics-studio.php',
    'direct' => '/inferential-statistics-workspace.php',
  ],
  'qual' => [
    'slug'           => 'qual',
    'name'           => 'Qualitative Analysis Studio',
    'mark'           => '/Qualitative Analysis.png',
    'description'    => 'Move from raw text to trustworthy qualitative interpretation. Code responses, build a codebook, develop evidence-supported themes, and review trustworthiness.',
    'status'         => 'dev',
    'status_label'   => 'In development',
    'accent'         => '#1e5c3a',
    'accent_deep'    => '#174d30',
    'accent_soft'    => '#e8f5ee',
    'primary_action' => 'Open Qualitative Studio',
    'primary_route'  => '/qual-studio-workspace.php',
    'sample'         => [
      'project' => 'Workplace Equity Survey, 2026',
      'context' => '412 open-ended responses',
    ],
    'route'  => '/qual-studio.php',
    'direct' => '/qual-studio-workspace.php',
  ],
  'basic' => [
    'slug'           => 'basic',
    'kind'           => 'app',
    'name'           => 'ReliCheck Basic',
    'mark'           => '/relicheck-basic-icon.svg',
    'description'    => 'Free starter: build a simple survey, collect up to 25 responses, and get a Basic SIRI and Basic RSSI score. Upgrade any time for the full review.',
    'status'         => 'beta',
    'status_label'   => 'Free',
    'accent'         => '#64748b',
    'accent_deep'    => '#334155',
    'accent_soft'    => '#f1f5f9',
    'primary_action' => 'Start a Basic survey',
    'primary_route'  => '/relicheck-basic-workspace.php',
    'sample'         => [
      'project' => 'Quick Pulse',
      'context' => 'up to 25 responses',
    ],
    'route'  => '/relicheck-basic.php',
    'direct' => '/relicheck-basic-workspace.php',
  ],
  'rssi' => [
    'slug'           => 'rssi',
    'kind'           => 'app',
    'name'           => 'ReliCheck Survey Strength Index',
    'mark'           => '/rssi-icon.png',
    'description'    => 'Evaluate whether collected survey responses are strong enough to interpret, explain, and defend.',
    'status'         => 'live',
    'status_label'   => 'Live',
    'accent'         => '#007AFF',
    'accent_deep'    => '#0A6FE8',
    'accent_soft'    => '#F1F6FF',
    'primary_action' => 'Run Strength Report',
    'primary_route'  => '/rssi-report.php',
    'sample'         => [
      'project' => 'Workplace Equity Survey, 2026',
      'context' => '412 responses',
    ],
    'route'  => '/rssi.php',
    'direct' => '/rssi-app.php',
  ],
];
