<?php
// ReliCheck Studio Registry
// -------------------------------------------------------------------
// Source of truth for which studios exist and their identity. Used by:
//   - Platform Shell welcome (the studio picker tiles)
//   - Studio Template (the identity strip at the top of a studio page)
// Item visibility per studio lives in _studio_items_catalog.php.
//
// To add a new studio: add a key here (slug as the array key), then add
// items that target it in the catalog. The status field drives what shows
// on the welcome picker and what's editable in a given pass.
//   live = published; beta = limited use; demo = read-only sample;
//   dev  = in development (visible to internal users only)

return [
  'survey' => [
    'slug'           => 'survey',
    'kind'           => 'app',
    'name'           => 'Survey Development System',
    'mark'           => '/Survey Studio.png',
    'description'    => 'Build or bring in a survey, check its development strength, prepare it for launch, collect responses, and evaluate the evidence.',
    'status'         => 'live',
    'status_label'   => 'Live',
    'accent'         => '#E07820',
    'accent_deep'    => '#b85f10',
    'accent_soft'    => '#fef3e8',
    'primary_action' => 'Open the development workspace',
    'primary_route'  => '/develop.php?db=1',
    'sample'         => [
      'project' => 'Workplace Equity Survey, 2026',
      'context' => '412 responses',
    ],
    'route'  => '/survey-dev.php',
    'direct' => '/develop.php?db=1&start=choose',
  ],
  'da' => [
    'slug'           => 'da',
    'category'       => 'research',
    'name'           => 'Descriptive Studio',
    'mark'           => '/Descriptive%20Studio.png',
    'description'    => 'Explore your data through frequencies, distributions, cross-tabs, group summaries, and scale scores before drawing conclusions.',
    'status'         => 'live',
    'status_label'   => 'Live',
    'accent'         => '#c0392b',
    'accent_deep'    => '#922b21',
    'accent_soft'    => '#fdecea',
    'primary_action' => 'Open Descriptive Studio',
    'primary_route'  => '/descriptive-analysis-workspaceV4.php',
    'sample'         => [
      'project' => 'Workplace Equity Survey, 2026',
      'context' => '412 responses',
    ],
    'route'  => '/studio-da.php',
    'direct' => '/descriptive-analysis-workspaceV4.php',
  ],
  'is' => [
    'slug'           => 'is',
    'category'       => 'research',
    'name'           => 'Inferential Studio',
    'mark'           => '/Inferential%20Studio.png',
    'description'    => 'Test hypotheses, compare groups, examine relationships, and quantify effect sizes with guided inferential analysis.',
    'status'         => 'live',
    'status_label'   => 'Live',
    'accent'         => '#1d4ed8',
    'accent_deep'    => '#1741b6',
    'accent_soft'    => '#eff2ff',
    'primary_action' => 'Open Inferential Studio',
    'primary_route'  => '/inferential-statistics-workspaceV4.php',
    'sample'         => [
      'project' => 'Workplace Equity Survey, 2026',
      'context' => '412 responses',
    ],
    'route'  => '/studio-is.php',
    'direct' => '/inferential-statistics-workspaceV4.php',
  ],
  'qual' => [
    'slug'           => 'qual',
    'category'       => 'research',
    'name'           => 'Qualitative Analysis Studio',
    'mark'           => '/Qualitative%20Analysis.png',
    'description'    => 'Move from raw text to trustworthy qualitative interpretation. Code responses, build a codebook, develop evidence-supported themes, and review trustworthiness.',
    'status'         => 'live',
    'status_label'   => 'Live',
    'accent'         => '#1e5c3a',
    'accent_deep'    => '#174d30',
    'accent_soft'    => '#e8f5ee',
    'primary_action' => 'Open Qualitative Studio',
    'primary_route'  => '/qual-studio-workspaceV4.php',
    'sample'         => [
      'project' => 'Workplace Equity Survey, 2026',
      'context' => '412 open-ended responses',
    ],
    'route'  => '/qual-studio.php',
    'direct' => '/qual-studio-workspaceV4.php',
  ],
  'mm' => [
    'slug'           => 'mm',
    'category'       => 'research',
    'name'           => 'MM Studio',
    'mark'           => '/MM%20Studio.png',
    'description'    => 'Connect qualitative and quantitative evidence, build themes, compare groups, and create mixed-methods displays.',
    'status'         => 'beta',
    'status_label'   => 'Beta',
    'accent'         => '#6d4ad8',
    'accent_deep'    => '#5a37c0',
    'accent_soft'    => '#efeafd',
    'primary_action' => 'Build Joint Display',
    'primary_route'  => '/joint-display.php',
    'sample'         => [
      'project' => 'Belonging & Retention Study',
      'context' => '212 surveys, 18 interviews',
    ],
    'route'  => '/studio-mm.php',
    'direct' => '/mmstudioV4.php',
  ],
  'tia' => [
    'slug'           => 'tia',
    'category'       => 'assessment',
    'name'           => 'TIA Studio',
    'mark'           => '/TIA%20Studio.png',
    'description'    => 'Analyze tests, items, rubrics, difficulty, discrimination, and cognitive demand.',
    'status'         => 'dev',
    'status_label'   => 'In development',
    'accent'         => '#0e8a6f',
    'accent_deep'    => '#0b6e58',
    'accent_soft'    => '#e3f5ee',
    'primary_action' => 'Run Item Analysis',
    'primary_route'  => '/item-quality.php',
    'sample'         => [
      'project' => '8th Grade Math Test, 2026',
      'context' => '184 students, 40 items',
    ],
    'route'  => '/studio-tia.php',
    'direct' => '/tia-wizard.php?step=1',
  ],
  '360' => [
    'slug'           => '360',
    'category'       => 'assessment',
    'name'           => '360 Studio',
    'mark'           => '/360%20Studio.png',
    'description'    => 'Analyze multi-rater feedback across self, peer, manager, and direct-report perspectives.',
    'status'         => 'demo',
    'status_label'   => 'Demo',
    'accent'         => '#2563eb',
    'accent_deep'    => '#1d4ed8',
    'accent_soft'    => '#e6efff',
    'primary_action' => 'Open Perception Gaps',
    'primary_route'  => '/rater-group-comparison.php',
    'sample'         => [
      'project' => 'Leadership 360, Cohort 4',
      'context' => '12 ratees, 84 raters',
    ],
    'route'  => '/studio-360.php',
    'direct' => '/360-wizard.php?step=1',
  ],
  'basic' => [
    'slug'           => 'basic',
    'kind'           => 'app',
    'name'           => 'ReliCheck Basic',
    'mark'           => '/ReliCheck%20Basic.png',
    'description'    => 'Free starter: build a simple survey, collect up to 25 responses, and get a Basic SIRI and Basic RSSI score. Upgrade any time for the full review.',
    'status'         => 'live',
    'status_label'   => 'Live',
    'accent'         => '#64748b',
    'accent_deep'    => '#334155',
    'accent_soft'    => '#f1f5f9',
    'primary_action' => 'Start a Basic survey',
    'primary_route'  => '/relicheck-basic-workspace.php',
    'sample'         => [
      'project' => 'Quick Pulse',
      'context' => 'up to 25 responses',
    ],
    'route'  => '/relicheck-basic.php',
    'direct' => '/relicheck-basic-workspace.php',
  ],
  'rssi' => [
    'slug'           => 'rssi',
    'kind'           => 'app',
    'name'           => 'ReliCheck Survey Strength Index',
    'mark'           => '/rssi-icon.png',
    'description'    => 'Evaluate whether collected survey responses are strong enough to interpret, explain, and defend.',
    'status'         => 'live',
    'status_label'   => 'Live',
    'accent'         => '#2D8DFF',
    'accent_deep'    => '#0A6FE8',
    'accent_soft'    => '#EAF2FE',
    'primary_action' => 'Run Strength Report',
    'primary_route'  => '/rssi-report.php',
    'sample'         => [
      'project' => 'Workplace Equity Survey, 2026',
      'context' => '412 responses',
    ],
    'route'  => '/rssi.php',
    'direct' => '/rssi-app.php',
  ],
  'text' => [
    'slug'           => 'text',
    'kind'           => 'app',
    'name'           => 'ReliCheck OpenText',
    'mark'           => '/OpenText.png',
    'description'    => 'Fast AI-powered first pass on open-ended text. See emerging themes, explore patterns, and turn qualitative responses into measurable variables.',
    'status'         => 'live',
    'status_label'   => 'Live',
    'accent'         => '#D97706',
    'accent_deep'    => '#92400E',
    'accent_soft'    => '#FEF3C7',
    'primary_action' => 'Open ReliCheck OpenText',
    'primary_route'  => '/text-analyzer.php',
    'sample'         => [
      'project' => 'Employee Feedback Survey, 2026',
      'context' => '210 open-ended responses',
    ],
    'route'  => '/text-analyzer.php',
    'direct' => '/text-analyzer.php',
  ],
];
