<?php
// ReliCheck Studio Items Catalog
// -------------------------------------------------------------------
// Defines the six-section methodology arc and the items inside each section.
// The Studio Template reads this and renders the left rail filtered by the
// current studio.
//
// Each item is an array:
//   key      = stable id used to mark the active item from a page
//   label    = user-facing text
//   icon     = inline SVG markup (already has class="tool-ico")
//   route    = relative URL (optional; default '#')
//   badge    = small pill text shown next to the item (optional)
//   studios  = list of studio slugs that show this item (optional;
//              if absent, the item is universal and shows in all studios)
//
// The six section keys are LOAD-BEARING per [[relicheck-studio-shell]]:
// do not rename or restructure without updating the memory rule.

return [

  // ============================================================
  [
    'key'      => 'overview',
    'label'    => 'Overview',
    'question' => 'what do we have?',
    'items' => [
      ['key' => 'project_snapshot', 'label' => 'Project Snapshot',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="8" height="8" rx="1.5"/><rect x="13" y="3" width="8" height="5" rx="1.5"/><rect x="13" y="10" width="8" height="11" rx="1.5"/><rect x="3" y="13" width="8" height="8" rx="1.5"/></svg>'],
      ['key' => 'purpose', 'label' => 'Purpose & Research Question',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1.5" fill="currentColor"/></svg>'],
      ['key' => 'sample_sources', 'label' => 'Sample & Data Sources',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8z"/><path d="M2 21v-1a5 5 0 0 1 5-5h4a5 5 0 0 1 5 5v1"/><path d="M16 11a4 4 0 1 0 0-8"/><path d="M22 21v-1a5 5 0 0 0-4-4.9"/></svg>'],
      // Removed (per feedback): Overall Findings (duplicates Project Snapshot
      // + Key Findings + Findings) and Data Readiness (consolidated into Data
      // Quality — same question, two pages).
      ['key' => 'data_quality', 'label' => 'Data Quality',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2l8 4v6c0 5-3.5 8.5-8 10-4.5-1.5-8-5-8-10V6z"/><path d="M9 12l2 2 4-4"/></svg>'],
    ],
  ],

  // ============================================================
  [
    'key'      => 'instrument_quality',
    'label'    => 'Instrument Quality',
    'question' => 'can we trust it?',
    'items' => [
      ['key' => 'strength_index', 'label' => 'ReliCheck Strength Index',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2l2.6 5.3 5.8.8-4.2 4.1 1 5.8L12 15.3 6.8 18l1-5.8L3.6 8.1l5.8-.8z"/></svg>'],
      ['key' => 'reliability', 'label' => 'Reliability',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12a9 9 0 1 1-3-6.7"/><polyline points="21 4 21 10 15 10"/></svg>'],
      ['key' => 'validity', 'label' => 'Validity',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M16 8l-7 7-3-3"/></svg>'],
      ['key' => 'dignity_framing', 'label' => 'Dignity / Framing', 'badge' => 'pre-data',
       'studios' => ['survey', 'strength-survey'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 21s-7-4-7-12V5l7-2 7 2v4c0 8-7 12-7 12z"/><circle cx="12" cy="10" r="2.2"/><path d="M8.5 16.5a3.5 3.5 0 0 1 7 0"/></svg>'],
      ['key' => 'access', 'label' => 'Access', 'badge' => 'pre-data',
       'studios' => ['survey', 'strength-survey'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="4" r="1.6"/><path d="M5 8h14"/><path d="M9 8v4l-2 7"/><path d="M15 8v4l2 7"/><path d="M9 12h6"/></svg>'],
      ['key' => 'construct_definition', 'label' => 'Construct Definition', 'badge' => 'pre-data',
       'studios' => ['survey', 'strength-survey'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="4" width="16" height="16" rx="2"/><path d="M8 9h8"/><path d="M8 13h5"/></svg>'],
      ['key' => 'purpose_alignment', 'label' => 'Purpose Alignment', 'badge' => 'pre-data',
       'studios' => ['survey', 'strength-survey'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="4.5"/><circle cx="12" cy="12" r="1"/></svg>'],
      ['key' => 'dimension_coverage', 'label' => 'Dimension / Domain Coverage', 'badge' => 'pre-data',
       'studios' => ['survey', 'strength-survey'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v18"/><path d="M3 12h18"/><circle cx="12" cy="12" r="9"/></svg>'],
      ['key' => 'item_construct_alignment', 'label' => 'Item-to-Construct Alignment', 'badge' => 'pre-data',
       'studios' => ['survey', 'strength-survey'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="5" y1="7" x2="11" y2="7"/><line x1="5" y1="12" x2="11" y2="12"/><line x1="5" y1="17" x2="11" y2="17"/><path d="M15 7l2 2 3-4"/></svg>'],
      ['key' => 'response_option_validity', 'label' => 'Response-Option Validity', 'badge' => 'pre-data',
       'studios' => ['survey', 'strength-survey'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="6" cy="7" r="2"/><circle cx="6" cy="14" r="2"/><line x1="10" y1="7" x2="19" y2="7"/><line x1="10" y1="14" x2="19" y2="14"/></svg>'],
      // ── Reliability Readiness (pre-data design lenses; 5 components / 35 pts).
      //    ALPHA FENCE: no alpha/omega/item-total/inter-item/factor analysis. ──
      ['key' => 'scale_structure_readiness', 'label' => 'Scale Structure Readiness', 'badge' => 'pre-data',
       'studios' => ['survey', 'strength-survey'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="8.5" y="14" width="7" height="7" rx="1"/><path d="M6.5 10v2h11v-2"/><path d="M12 12v2"/></svg>'],
      ['key' => 'item_clarity', 'label' => 'Item Clarity / Wording Consistency', 'badge' => 'pre-data',
       'studios' => ['survey', 'strength-survey'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 5h16"/><path d="M4 10h10"/><path d="M4 15h16"/><path d="M4 20h7"/></svg>'],
      ['key' => 'response_scale_consistency', 'label' => 'Response Scale Consistency', 'badge' => 'pre-data',
       'studios' => ['survey', 'strength-survey'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="3" y1="9" x2="21" y2="9"/><circle cx="7" cy="9" r="1.5"/><circle cx="12" cy="9" r="1.5"/><circle cx="17" cy="9" r="1.5"/><line x1="3" y1="16" x2="21" y2="16"/><circle cx="7" cy="16" r="1.5"/><circle cx="12" cy="16" r="1.5"/><circle cx="17" cy="16" r="1.5"/></svg>'],
      ['key' => 'redundancy_balance', 'label' => 'Redundancy Balance', 'badge' => 'pre-data',
       'studios' => ['survey', 'strength-survey'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="9" cy="12" r="6"/><circle cx="15" cy="12" r="6"/></svg>'],
      ['key' => 'administration_consistency', 'label' => 'Administration Consistency', 'badge' => 'pre-data',
       'studios' => ['survey', 'strength-survey'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18"/><path d="M8 2v4"/><path d="M16 2v4"/><path d="M7 13l2 2 4-4"/></svg>'],
      // ── Administration Readiness (pre-launch fielding lenses; 5 components / 15 pts).
      //    PRE-LAUNCH SCOPE: readiness to field responsibly/clearly/safely/practically;
      //    never survey results or post-administration data quality (that is RSSI). ──
      ['key' => 'respondent_instructions', 'label' => 'Respondent Instructions & Guidance', 'badge' => 'pre-launch',
       'studios' => ['survey', 'strength-survey'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 5h16"/><path d="M4 9h12"/><path d="M4 13h16"/><path d="M4 17h9"/><circle cx="19" cy="18" r="2.5"/></svg>'],
      ['key' => 'consent_privacy', 'label' => 'Consent, Privacy & Use Transparency', 'badge' => 'pre-launch',
       'studios' => ['survey', 'strength-survey'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3l7 3v5c0 5-3.5 8-7 9-3.5-1-7-4-7-9V6z"/><rect x="9" y="10" width="6" height="5" rx="1"/><path d="M10.5 10V8.5a1.5 1.5 0 0 1 3 0V10"/></svg>'],
      ['key' => 'fielding_plan', 'label' => 'Fielding Plan & Timing', 'badge' => 'pre-launch',
       'studios' => ['survey', 'strength-survey'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="17" rx="2"/><path d="M3 9h18"/><path d="M8 2v4"/><path d="M16 2v4"/><circle cx="12" cy="15" r="2.5"/><path d="M12 13.5V15l1 1"/></svg>'],
      ['key' => 'sensitive_safety', 'label' => 'Sensitive-Topic & Safety Readiness', 'badge' => 'pre-launch',
       'studios' => ['survey', 'strength-survey'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10.3 3.9 2.4 17.3a1.8 1.8 0 0 0 1.5 2.7h16.2a1.8 1.8 0 0 0 1.5-2.7L13.7 3.9a1.9 1.9 0 0 0-3.4 0z"/><path d="M12 9v4"/><circle cx="12" cy="16.5" r="0.6" fill="currentColor"/></svg>'],
      ['key' => 'completion_burden', 'label' => 'Completion Burden & Launch Logistics', 'badge' => 'pre-launch',
       'studios' => ['survey', 'strength-survey'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="13" r="8"/><path d="M12 13V8.5"/><path d="M12 13l3 2"/><path d="M9 2h6"/></svg>'],
      ['key' => 'administration_readiness', 'label' => 'Administration Readiness', 'badge' => 'pre-launch',
       'studios' => ['survey', 'strength-survey'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 12l4-4 4 4 6-6"/><polyline points="17 6 21 6 21 10"/><path d="M3 20h18"/></svg>'],
      ['key' => 'validity_readiness', 'label' => 'Validity Readiness', 'sub' => 'SDSI · 50-point validity domain', 'badge' => 'pre-launch',
       'studios' => ['survey', 'strength-survey'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3l8 4v5c0 4.5-3.2 7.8-8 9-4.8-1.2-8-4.5-8-9V7z"/><polyline points="9 12 11 14 15 9"/></svg>'],
      ['key' => 'reliability_readiness', 'label' => 'Reliability Readiness', 'sub' => '35-point reliability domain', 'badge' => 'pre-launch',
       'studios' => ['survey', 'strength-survey'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12a9 9 0 1 1-3-6.7"/><polyline points="21 4 21 9 16 9"/></svg>'],
      ['key' => 'siri_dashboard', 'label' => 'SIRI Dashboard', 'sub' => 'Full 100-point survey instrument readiness score', 'badge' => 'pre-launch',
       'studios' => ['survey', 'strength-survey'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>'],
      ['key' => 'construct_alignment', 'label' => 'Construct Alignment',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="5" width="18" height="3" rx="1"/><rect x="3" y="11" width="14" height="3" rx="1"/><rect x="3" y="17" width="10" height="3" rx="1"/></svg>'],
      ['key' => 'item_quality', 'label' => 'Item / Prompt Quality',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="4 8 6 10 10 6"/><line x1="13" y1="8" x2="21" y2="8"/><polyline points="4 16 6 18 10 14"/><line x1="13" y1="16" x2="21" y2="16"/></svg>'],
      ['key' => 'bias_review', 'label' => 'Bias & Clarity Review',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="7"/><path d="M21 21l-4.3-4.3"/><path d="M11 8v3l2 1"/></svg>'],
      ['key' => 'scale_structure', 'label' => 'Scale Structure',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="6" cy="8" r="2.5"/><circle cx="18" cy="8" r="2.5"/><circle cx="6" cy="16" r="2.5"/><circle cx="18" cy="16" r="2.5"/><line x1="6" y1="10.5" x2="6" y2="13.5"/><line x1="18" y1="10.5" x2="18" y2="13.5"/><line x1="8.5" y1="8" x2="15.5" y2="8"/><line x1="8.5" y1="16" x2="15.5" y2="16"/></svg>'],
      ['key' => 'factor_readiness', 'label' => 'Factor Readiness',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 12L9 6l4 4 8-8"/><polyline points="14 2 21 2 21 9"/></svg>'],
      ['key' => 'response_scale_review', 'label' => 'Response Scale Review',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="3" y1="12" x2="21" y2="12"/><circle cx="6" cy="12" r="1.5"/><circle cx="10" cy="12" r="1.5"/><circle cx="14" cy="12" r="1.5"/><circle cx="18" cy="12" r="1.5"/><line x1="3" y1="7" x2="21" y2="7" stroke-dasharray="2 2"/><line x1="3" y1="17" x2="21" y2="17" stroke-dasharray="2 2"/></svg>'],
      ['key' => 'trustworthiness', 'label' => 'Trustworthiness', 'badge' => 'qual',
       'studios' => ['mm'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 21s-7-4-7-12V5l7-2 7 2v4c0 8-7 12-7 12z"/><path d="M9 12l2 2 4-4"/></svg>'],
      ['key' => 'inter_rater_agreement', 'label' => 'Inter-rater Agreement',
       'studios' => ['mm', 'tia', '360'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="7" cy="8" r="3"/><circle cx="17" cy="8" r="3"/><path d="M7 14v6M17 14v6"/><path d="M7 17h10"/></svg>'],
    ],
  ],

  // ============================================================
  [
    'key'      => 'descriptive',
    'label'    => 'Descriptive Analysis',
    'question' => 'what does it show?',
    'items' => [
      ['key' => 'frequencies', 'label' => 'Frequencies', 'strand' => 'QUAN',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="12" width="3" height="8" rx="0.5"/><rect x="10" y="6" width="3" height="14" rx="0.5"/><rect x="16" y="10" width="3" height="10" rx="0.5"/></svg>'],
      ['key' => 'means_distributions', 'label' => 'Means & Distributions', 'strand' => 'QUAN',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 18c3 0 4-12 9-12s6 12 9 12"/></svg>'],
      ['key' => 'cross_tabs', 'label' => 'Cross-Tabs', 'strand' => 'QUAN',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="1.5"/><line x1="3" y1="9" x2="21" y2="9"/><line x1="3" y1="15" x2="21" y2="15"/><line x1="9" y1="3" x2="9" y2="21"/><line x1="15" y1="3" x2="15" y2="21"/></svg>'],
      ['key' => 'group_summaries', 'label' => 'Group Summaries', 'strand' => 'QUAN',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="8" cy="8" r="3"/><circle cx="16" cy="8" r="3"/><circle cx="12" cy="16" r="3"/></svg>'],
      ['key' => 'item_theme_summaries', 'label' => 'Item / Theme Summaries', 'strand' => 'MM',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 12L9 12"/><path d="M16 8l4 4-4 4"/><path d="M4 4v16"/></svg>'],
      ['key' => 'top_bottom_items', 'label' => 'Top &amp; Bottom Items', 'strand' => 'QUAN',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M7 10l5-5 5 5"/><path d="M7 14l5 5 5-5"/></svg>'],
      ['key' => 'scale_scores', 'label' => 'Scale Scores', 'strand' => 'QUAN',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>'],
      ['key' => 'missing_data', 'label' => 'Missing Data', 'strand' => 'QUAN',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="5" cy="12" r="1.4"/><circle cx="12" cy="12" r="1.4"/><circle cx="19" cy="12" r="1.4"/><path d="M3 6h18M3 18h18" stroke-dasharray="2 3"/></svg>'],
      ['key' => 'themes_codes', 'label' => 'Themes & Codes', 'badge' => 'qual', 'strand' => 'QUAL',
       'studios' => ['survey', 'mm'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 5h16M4 10h16M4 15h10M4 20h6"/><circle cx="20" cy="20" r="2"/></svg>'],
      ['key' => 'codebook_builder', 'label' => 'Codebook Builder', 'badge' => 'qual', 'strand' => 'QUAL',
       'studios' => ['mm'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 6h16v14H4z"/><path d="M4 6L2 4"/><line x1="8" y1="10" x2="16" y2="10"/><line x1="8" y1="14" x2="14" y2="14"/></svg>'],
      ['key' => 'theme_by_group', 'label' => 'Theme by Group', 'badge' => 'qual', 'strand' => 'QUAL',
       'studios' => ['mm'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg>'],
      ['key' => 'qual_to_quant', 'label' => 'Qual → Quant', 'badge' => 'qual', 'strand' => 'MM',
       'studios' => ['mm'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 12h12"/><polyline points="11 8 15 12 11 16"/><rect x="16" y="4" width="5" height="16" rx="1"/></svg>'],
      ['key' => 'exemplar_quotes', 'label' => 'Exemplar Quotes', 'badge' => 'qual', 'strand' => 'QUAL',
       'studios' => ['survey', 'mm'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M7 7c-1.5 0-2.5 1.2-2.5 2.7 0 1.4.8 2.3 2 2.3 0 2-1 3-2.5 3"/><path d="M16 7c-1.5 0-2.5 1.2-2.5 2.7 0 1.4.8 2.3 2 2.3 0 2-1 3-2.5 3"/></svg>'],
      ['key' => 'theme_cooccurrence', 'label' => 'Theme Co-occurrence', 'badge' => 'qual', 'strand' => 'QUAL',
       'studios' => ['mm'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="8" cy="12" r="4"/><circle cx="16" cy="12" r="4"/></svg>'],
    ],
  ],

  // ============================================================
  [
    'key'      => 'inferential',
    'label'    => 'Inferential Analysis',
    'question' => 'what can we test?',
    'items' => [
      ['key' => 'recommended_analyses', 'label' => 'Recommended Analyses',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 18h6"/><path d="M10 21h4"/><path d="M12 3a7 7 0 0 1 5 11.9c-.6.7-1 1.4-1 2.1H8c0-.7-.4-1.4-1-2.1A7 7 0 0 1 12 3z"/></svg>'],
      ['key' => 't_test', 'label' => 'T-Test', 'strand' => 'QUAN',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 5h8"/><path d="M9 5v15"/><line x1="15" y1="10" x2="21" y2="20"/><line x1="21" y1="10" x2="15" y2="20"/></svg>'],
      ['key' => 'anova', 'label' => 'ANOVA', 'strand' => 'QUAN',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="14" width="3" height="6" rx="0.5"/><rect x="8" y="10" width="3" height="10" rx="0.5"/><rect x="13" y="6" width="3" height="14" rx="0.5"/><rect x="18" y="12" width="3" height="8" rx="0.5"/></svg>'],
      ['key' => 'chi_square', 'label' => 'Chi-Square', 'strand' => 'QUAN',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="6" y1="6" x2="18" y2="18"/><line x1="18" y1="6" x2="6" y2="18"/><rect x="3" y="3" width="18" height="18" rx="2"/></svg>'],
      ['key' => 'correlation', 'label' => 'Correlation', 'strand' => 'QUAN',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 20L20 4"/><circle cx="6" cy="18" r="1"/><circle cx="10" cy="14" r="1"/><circle cx="13" cy="11" r="1"/><circle cx="17" cy="7" r="1"/></svg>'],
      ['key' => 'effect_sizes', 'label' => 'Effect Sizes', 'strand' => 'QUAN',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="5" y1="19" x2="19" y2="5"/><circle cx="7" cy="7" r="3"/><circle cx="17" cy="17" r="3"/></svg>'],
      ['key' => 'paired_t_test', 'label' => 'Paired T-Test', 'strand' => 'QUAN',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 6h7M4 18h7"/><path d="M11 6l-2 6 2 6"/><path d="M14 6h6M14 12h6M14 18h6"/></svg>'],
      ['key' => 'welch_anova', 'label' => 'Welch ANOVA', 'strand' => 'QUAN',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="12" width="3" height="8" rx="0.5"/><rect x="8" y="8" width="3" height="12" rx="0.5"/><rect x="13" y="4" width="3" height="16" rx="0.5"/><rect x="18" y="10" width="3" height="10" rx="0.5"/><path d="M2 22h20" stroke-dasharray="2 2"/></svg>'],
      ['key' => 'post_hoc', 'label' => 'Post-Hoc Comparison', 'strand' => 'QUAN',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="6" cy="6" r="3"/><circle cx="18" cy="6" r="3"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="18" r="3"/><line x1="6" y1="9" x2="6" y2="15"/><line x1="9" y1="6" x2="15" y2="6"/><line x1="18" y1="9" x2="18" y2="15"/><line x1="9" y1="18" x2="15" y2="18"/></svg>'],
      ['key' => 'regression', 'label' => 'Regression', 'strand' => 'QUAN',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="4" y1="20" x2="20" y2="6"/><circle cx="6" cy="18" r="1"/><circle cx="10" cy="14" r="1"/><circle cx="14" cy="10" r="1"/><circle cx="18" cy="6" r="1"/></svg>'],
      ['key' => 'confidence_interval', 'label' => 'Confidence Intervals', 'strand' => 'QUAN',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="4" y1="12" x2="20" y2="12"/><line x1="4" y1="8" x2="4" y2="16"/><line x1="20" y1="8" x2="20" y2="16"/><circle cx="12" cy="12" r="2.5" fill="currentColor" stroke="none"/></svg>'],
      ['key' => 'assumption_checks', 'label' => 'Assumption Checks', 'strand' => 'QUAN',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3l8 4v5c0 5-3.5 8-8 9-4.5-1-8-4-8-9V7z"/></svg>'],

      // MM Studio specific
      ['key' => 'joint_displays', 'label' => 'Joint Displays', 'badge' => 'MM', 'strand' => 'MM',
       'studios' => ['mm'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="8" height="16" rx="1"/><rect x="13" y="4" width="8" height="16" rx="1"/></svg>'],
      ['key' => 'convergence_divergence', 'label' => 'Convergence & Divergence', 'badge' => 'MM', 'strand' => 'MM',
       'studios' => ['mm'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 7l6 5-6 5"/><path d="M20 7l-6 5 6 5"/></svg>'],
      ['key' => 'coding_agreement', 'label' => 'Coding Agreement (&kappa;)', 'badge' => 'qual', 'strand' => 'QUAL',
       'studios' => ['mm'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 17l4-4 3 3 8-8"/><path d="M14 8h6v6"/></svg>'],
      ['key' => 'pattern_matching', 'label' => 'Pattern Matching', 'badge' => 'qual', 'strand' => 'QUAL',
       'studios' => ['mm'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/><line x1="10" y1="6.5" x2="14" y2="6.5"/><line x1="10" y1="17.5" x2="14" y2="17.5"/><line x1="6.5" y1="10" x2="6.5" y2="14"/><line x1="17.5" y1="10" x2="17.5" y2="14"/></svg>'],
      ['key' => 'meta_inferences', 'label' => 'Meta-inferences', 'badge' => 'MM', 'strand' => 'MM',
       'studios' => ['mm'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="6" cy="6" r="3"/><circle cx="18" cy="6" r="3"/><circle cx="12" cy="18" r="3"/><path d="M6 9l6 6M18 9l-6 6"/></svg>'],

      // TIA Studio specific
      ['key' => 'item_difficulty', 'label' => 'Item Difficulty',
       'studios' => ['tia'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 20V8l8-5 8 5v12"/><path d="M9 20v-7h6v7"/></svg>'],
      ['key' => 'item_discrimination', 'label' => 'Item Discrimination',
       'studios' => ['tia'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 12c4-7 12-7 16 0"/><path d="M4 12c4 7 12 7 16 0"/></svg>'],
      ['key' => 'distractor_analysis', 'label' => 'Distractor Analysis',
       'studios' => ['tia'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="6" cy="12" r="3"/><circle cx="14" cy="6" r="3"/><circle cx="14" cy="18" r="3"/><circle cx="20" cy="12" r="1.5"/></svg>'],
      ['key' => 'answer_key_validation', 'label' => 'Answer Key Validation',
       'studios' => ['tia'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M7 12l3 3 7-7"/></svg>'],
      ['key' => 'point_biserial', 'label' => 'Point-Biserial',
       'studios' => ['tia'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="4" y1="20" x2="20" y2="4"/><circle cx="4" cy="20" r="1.5"/><circle cx="20" cy="4" r="1.5"/></svg>'],
      ['key' => 'dif', 'label' => 'Differential Item Functioning',
       'studios' => ['tia'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 18c3-3 5-9 8-9s5 6 8 9"/><path d="M4 14c3-3 5-9 8-9s5 6 8 9"/></svg>'],
      ['key' => 'irt', 'label' => 'IRT (Rasch / 2PL)',
       'studios' => ['tia'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 20c4-12 14-12 18 0"/><circle cx="6" cy="14" r="1"/><circle cx="12" cy="9" r="1"/><circle cx="18" cy="14" r="1"/></svg>'],

      // 360 Studio specific
      ['key' => 'perception_gaps', 'label' => 'Perception Gaps',
       'studios' => ['360'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="8" cy="9" r="3"/><circle cx="16" cy="15" r="3"/><path d="M11 11l2 2" stroke-dasharray="2 2"/></svg>'],
      ['key' => 'rater_ratee_matrix', 'label' => 'Rater-by-Ratee Matrix',
       'studios' => ['360'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="6" height="6" rx="1"/><rect x="11" y="3" width="6" height="6" rx="1"/><rect x="3" y="11" width="6" height="6" rx="1"/><rect x="11" y="11" width="6" height="6" rx="1"/><rect x="3" y="19" width="6" height="2" rx="1"/></svg>'],
      ['key' => 'rater_group_comparison', 'label' => 'Rater Group Comparison',
       'studios' => ['360'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="6" cy="6" r="2.5"/><circle cx="18" cy="6" r="2.5"/><circle cx="6" cy="18" r="2.5"/><circle cx="18" cy="18" r="2.5"/><line x1="8.5" y1="6" x2="15.5" y2="6"/><line x1="8.5" y1="18" x2="15.5" y2="18"/></svg>'],
      ['key' => 'confidentiality_threshold', 'label' => 'Confidentiality Threshold',
       'studios' => ['360'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="6" y="11" width="12" height="9" rx="1.5"/><path d="M9 11V8a3 3 0 0 1 6 0v3"/></svg>'],
      ['key' => 'comment_theme', 'label' => 'Comment Theme',
       'studios' => ['360'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"/></svg>'],
      ['key' => 'development_plan', 'label' => 'Development Plan',
       'studios' => ['360'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="9" y1="13" x2="15" y2="13"/><line x1="9" y1="17" x2="13" y2="17"/></svg>'],
      ['key' => 'cohort_summary', 'label' => 'Cohort Summary',
       'studios' => ['360'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="9" cy="7" r="3"/><circle cx="16" cy="9" r="3"/><circle cx="12" cy="16" r="3"/></svg>'],
      ['key' => 'competency_profiles', 'label' => 'Competency Profiles',
       'studios' => ['360'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="4 20 9 14 13 17 20 7"/></svg>'],
      ['key' => 'profile_clustering', 'label' => 'Profile Clustering',
       'studios' => ['360'],
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="7" cy="9" r="3"/><circle cx="17" cy="9" r="3"/><circle cx="12" cy="17" r="3"/></svg>'],
    ],
  ],

  // ============================================================
  [
    'key'      => 'interpretation',
    'label'    => 'Interpretation',
    'question' => 'what does it mean?',
    'items' => [
      ['key' => 'key_findings', 'label' => 'Key Findings',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="8" cy="14" r="4"/><path d="M11 11l9-9"/><path d="M16 6l3 3"/></svg>'],
      ['key' => 'evidence_notes', 'label' => 'Evidence Notes',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M7 7c-1.5 0-2.5 1.2-2.5 2.7 0 1.4.8 2.3 2 2.3 0 2-1 3-2.5 3"/><path d="M16 7c-1.5 0-2.5 1.2-2.5 2.7 0 1.4.8 2.3 2 2.3 0 2-1 3-2.5 3"/></svg>'],
      ['key' => 'practical_meaning', 'label' => 'Practical Meaning',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 11V6a3 3 0 0 1 6 0v5"/><path d="M5 11h14l-1 9a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2z"/></svg>'],
      ['key' => 'limitations', 'label' => 'Limitations',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10.3 3.9L1.8 18a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0z"/><line x1="12" y1="9" x2="12" y2="13"/><circle cx="12" cy="17" r=".8" fill="currentColor"/></svg>'],
      ['key' => 'recommended_actions', 'label' => 'Recommended Actions',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><polyline points="10 8 14 12 10 16"/></svg>'],
      ['key' => 'teaching_moments', 'label' => 'Teaching Moments',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19V5a2 2 0 0 1 2-2h7v18H6a2 2 0 0 1-2-2z"/><path d="M13 3h5a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-5"/></svg>'],
      ['key' => 'ai_interpretation', 'label' => 'AI Interpretation',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2l1.8 4.2L18 8l-4.2 1.8L12 14l-1.8-4.2L6 8l4.2-1.8z"/><path d="M19 14l1 2.3L22 17l-2 1-1 2-1-2-2-1 2-1z"/><path d="M5 17l.8 1.8L7.5 19.5 5.8 20.3 5 22l-.8-1.7L2.5 19.5l1.7-.7z"/></svg>'],
      ['key' => 'decision_readiness', 'label' => 'Decision Readiness',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3l8 4v5c0 5-3.5 8-8 9-4.5-1-8-4-8-9V7z"/><polyline points="9 12 11 14 15 10"/></svg>'],
    ],
  ],

  // ============================================================
  [
    'key'      => 'reporting',
    'label'    => 'Reporting',
    'question' => 'how do we report it?',
    'items' => [
      ['key' => 'report_builder', 'label' => 'Report Builder',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><path d="M14 14h7v7h-7z" stroke-dasharray="2 3"/></svg>'],
      ['key' => 'executive_summary', 'label' => 'Executive Summary',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"/><path d="M14 3v6h6"/><line x1="8" y1="13" x2="16" y2="13"/></svg>'],
      ['key' => 'methodology', 'label' => 'Methodology',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 19l7-7 2 2-7 7H12z"/><path d="M18 13l-1.5-1.5"/><path d="M3 21l3-1 9-9-2-2-9 9z"/></svg>'],
      ['key' => 'findings', 'label' => 'Findings',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="3 17 9 11 13 15 21 7"/><polyline points="14 7 21 7 21 14"/></svg>'],
      ['key' => 'tables_figures', 'label' => 'Tables & Figures',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="4" width="18" height="16" rx="1.5"/><line x1="3" y1="10" x2="21" y2="10"/><line x1="3" y1="15" x2="21" y2="15"/><line x1="9" y1="4" x2="9" y2="20"/></svg>'],
      ['key' => 'recommendations', 'label' => 'Recommendations',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 11 12 14 22 4"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/></svg>'],
      ['key' => 'appendix', 'label' => 'Appendix',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 13l-7 8-7-8"/><path d="M19 5l-7 8-7-8"/></svg>'],
      ['key' => 'exports', 'label' => 'Exports',
       'icon' => '<svg class="tool-ico" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>'],
    ],
  ],
];
