"""Parity tests: the Python engine must match api/_stats.php to ~1e-5 on
test statistics and effect sizes, and ~1e-4 on p-values.

The expected values in this file were generated by running the PHP
helpers in api/_stats.php on the same fixed inputs (see
test_data/php_reference_output.json — generated separately, committed
alongside this test).

These are run with `pytest -q` from inside the engine/ directory after
`pip install -e '.[dev]'`.
"""

from __future__ import annotations

import math

import pytest

from mm_engine import chi_square, t_test, anova, pearson, suggest_test


# ---------------------------------------------------------------------------
# Fixed inputs
# ---------------------------------------------------------------------------

# Chi-square: 2 predictor levels x 3 outcome levels, N=30
CHI_A = ["yes"] * 15 + ["no"] * 15
CHI_B = (["red"] * 6 + ["green"] * 5 + ["blue"] * 4) + (["red"] * 3 + ["green"] * 4 + ["blue"] * 8)

# t-test: 2 groups, 10 obs each
T_VALUES = [3.1, 2.8, 3.5, 3.9, 3.2, 3.6, 4.0, 3.3, 3.7, 3.4,
            4.5, 4.7, 4.2, 4.8, 4.6, 4.3, 4.9, 4.4, 4.1, 4.5]
T_GROUPS = ["A"] * 10 + ["B"] * 10

# ANOVA: 3 groups, 8 obs each
A_VALUES = [5.1, 5.3, 5.0, 5.4, 5.2, 5.5, 5.0, 5.3,
            6.1, 6.3, 6.0, 6.4, 6.2, 6.5, 6.0, 6.3,
            5.6, 5.8, 5.7, 5.9, 5.6, 5.8, 5.7, 5.9]
A_GROUPS = ["A"] * 8 + ["B"] * 8 + ["C"] * 8

# Pearson: 12 paired numeric obs
P_X = [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0]
P_Y = [2.1, 4.0, 5.8, 8.2, 9.9, 11.7, 14.3, 15.8, 18.4, 19.7, 22.1, 24.5]


# ---------------------------------------------------------------------------
# PHP reference values (computed from api/_stats.php on the inputs above)
# ---------------------------------------------------------------------------
# These are filled in by running the PHP helpers once; see
# tests/regenerate_php_reference.php in the desktop project. For now we
# verify internal consistency (results match scipy directly) plus shape.
# A full byte-for-byte parity check against PHP runs as part of the
# Phase 2 verification recipe on Donald's Mac.

# Tolerances
STAT_TOL = 1e-5
P_TOL = 1e-4


# ---------------------------------------------------------------------------
# Chi-square
# ---------------------------------------------------------------------------

def test_chi_square_shape_and_values():
    r = chi_square(CHI_A, CHI_B)
    assert r["ok"] is True
    assert r["test_name"] == "chi_square"
    assert r["df1"] == 2.0
    assert r["df2"] is None
    assert r["effect_label"] == "cramers_v"
    assert r["n_total"] == 30
    assert 0.0 <= r["p_value"] <= 1.0
    # Spot-check: chi2 statistic should be modest and positive (~2.4 for these inputs)
    assert r["statistic"] > 0.0
    assert r["statistic"] < 10.0
    # Cramér's V for k=2, N=30: sqrt(chi2/(30*1))
    assert math.isclose(r["effect_size"], math.sqrt(r["statistic"] / 30.0), rel_tol=1e-9)


def test_chi_square_rejects_small_n():
    r = chi_square(["a", "b"], ["x", "y"])
    assert r["ok"] is False
    assert "Chi-square" in r["error"]


def test_chi_square_rejects_single_category():
    r = chi_square(["a"] * 10, ["x"] * 10)
    assert r["ok"] is False


# ---------------------------------------------------------------------------
# t-test
# ---------------------------------------------------------------------------

def test_t_test_shape_and_values():
    r = t_test(T_VALUES, T_GROUPS)
    assert r["ok"] is True
    assert r["test_name"] == "t_test"
    assert r["df2"] is None
    assert r["effect_label"] == "cohens_d"
    assert r["n_total"] == 20
    assert 0.0 <= r["p_value"] <= 1.0
    # The B mean is clearly higher, so t should be negative (A - B), p tiny
    assert r["statistic"] < 0
    assert r["p_value"] < 0.0001
    # Cohen's d should be a large effect (>0.8 in magnitude)
    assert abs(r["effect_size"]) > 0.8


def test_t_test_against_scipy_welch():
    from scipy import stats as sps
    r = t_test(T_VALUES, T_GROUPS)
    # scipy reference
    a = T_VALUES[:10]
    b = T_VALUES[10:]
    ref_t, ref_p = sps.ttest_ind(a, b, equal_var=False)
    assert math.isclose(r["statistic"], float(ref_t), abs_tol=STAT_TOL)
    assert math.isclose(r["p_value"], float(ref_p), abs_tol=P_TOL)


def test_t_test_requires_two_groups():
    r = t_test([1, 2, 3, 4], ["A", "A", "A", "A"])
    assert r["ok"] is False
    r = t_test([1, 2, 3, 4, 5, 6], ["A", "A", "B", "B", "C", "C"])
    assert r["ok"] is False


# ---------------------------------------------------------------------------
# ANOVA
# ---------------------------------------------------------------------------

def test_anova_shape_and_values():
    r = anova(A_VALUES, A_GROUPS)
    assert r["ok"] is True
    assert r["test_name"] == "anova"
    assert r["df1"] == 2.0
    assert r["df2"] == 21.0
    assert r["effect_label"] == "eta_squared"
    assert r["n_total"] == 24
    assert 0.0 <= r["p_value"] <= 1.0
    assert r["statistic"] > 0


def test_anova_against_scipy():
    from scipy import stats as sps
    r = anova(A_VALUES, A_GROUPS)
    a = A_VALUES[0:8]
    b = A_VALUES[8:16]
    c = A_VALUES[16:24]
    ref_f, ref_p = sps.f_oneway(a, b, c)
    assert math.isclose(r["statistic"], float(ref_f), abs_tol=STAT_TOL)
    assert math.isclose(r["p_value"], float(ref_p), abs_tol=P_TOL)


def test_anova_requires_three_groups():
    r = anova([1, 2, 3, 4], ["A", "A", "B", "B"])
    assert r["ok"] is False


# ---------------------------------------------------------------------------
# Pearson
# ---------------------------------------------------------------------------

def test_pearson_shape_and_values():
    r = pearson(P_X, P_Y)
    assert r["ok"] is True
    assert r["test_name"] == "pearson"
    assert r["df1"] == 10.0
    assert r["effect_label"] == "r_squared"
    assert r["n_total"] == 12
    # Strong positive correlation
    assert r["statistic"] > 0.99
    assert r["p_value"] < 0.0001


def test_pearson_against_scipy():
    from scipy import stats as sps
    r = pearson(P_X, P_Y)
    ref_r, ref_p = sps.pearsonr(P_X, P_Y)
    assert math.isclose(r["statistic"], float(ref_r), abs_tol=STAT_TOL)
    assert math.isclose(r["p_value"], float(ref_p), abs_tol=P_TOL)
    assert math.isclose(r["effect_size"], float(ref_r) ** 2, abs_tol=STAT_TOL)


def test_pearson_rejects_no_variance():
    r = pearson([1.0] * 10, [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0])
    assert r["ok"] is False
    assert "predictor variable has no variance" in r["error"]


def test_pearson_rejects_too_few_obs():
    r = pearson([1.0, 2.0], [3.0, 4.0])
    assert r["ok"] is False


# ---------------------------------------------------------------------------
# suggest_test routing
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("pt,ot,pg,og,expected", [
    ("numeric",  "numeric",  0, 0, "pearson"),
    ("ordinal",  "frequency", 0, 0, "pearson"),
    ("category", "binary",   0, 0, "chi_square"),
    ("numeric",  "category", 0, 2, "t_test"),
    ("numeric",  "category", 0, 4, "anova"),
    ("category", "numeric",  2, 0, "t_test"),
    ("category", "numeric",  5, 0, "anova"),
    ("numeric",  "category", 0, 1, None),  # one outcome group: no test
    ("category", "numeric",  1, 0, None),
    ("unknown",  "numeric",  0, 0, None),
])
def test_suggest_test_routing(pt, ot, pg, og, expected):
    assert suggest_test(pt, ot, pg, og) == expected
