-- Phase 31b seed: ReliCheck email departments, launch templates, and event bindings.
--
-- IMPORTANT: select the database first (drop-down at the top-left of phpMyAdmin
-- should read "dbs15641829") before running. The USE statement below is a
-- belt-and-braces guard.
--
-- Depends on: schema_phase31.sql (creates the tables) and schema_phase32.sql
-- (preferences). Re-runnable: uses INSERT IGNORE / ON DUPLICATE KEY UPDATE so
-- you can adjust copy and re-run safely.
--
-- Body HTML in this file is the INNER content only; the renderer
-- (api/_email_renderer.php) wraps it in the standard ReliCheck shell with
-- header, primary button, footer, and (when applicable) unsubscribe link.
-- Use {{first_name}}, {{survey_name}}, etc. for variable substitution.

USE dbs15641829;

SET NAMES utf8mb4;

-- ---------------------------------------------------------------------------
-- 1. The eleven official departments.
-- ---------------------------------------------------------------------------
INSERT INTO email_departments (code, display_name, sender_email, email_class, audience) VALUES
  ('hr',          'ReliCheck HR',          'hr@relichecksurvey.com',          'operational',   'employee'),
  ('support',     'ReliCheck Support',     'support@relichecksurvey.com',     'transactional', 'both'),
  ('legal',       'ReliCheck Legal',       'legal@relichecksurvey.com',       'legal',         'both'),
  ('welcome',     'ReliCheck Welcome',     'welcome@relichecksurvey.com',     'transactional', 'customer'),
  ('marketing',   'ReliCheck Marketing',   'marketing@relichecksurvey.com',   'marketing',     'both'),
  ('membership',  'ReliCheck Membership',  'membership@relichecksurvey.com',  'operational',   'both'),
  ('services',    'ReliCheck Services',    'services@relichecksurvey.com',    'operational',   'both'),
  ('privacy',     'ReliCheck Privacy',     'privacy@relichecksurvey.com',     'privacy',       'both'),
  ('terms',       'ReliCheck Terms',       'terms@relichecksurvey.com',       'legal',         'both'),
  ('sales',       'ReliCheck Sales',       'sales@relichecksurvey.com',       'sales',         'both'),
  ('billing',     'ReliCheck Billing',     'billing@relichecksurvey.com',     'billing',       'both')
ON DUPLICATE KEY UPDATE
  display_name = VALUES(display_name),
  email_class  = VALUES(email_class),
  audience     = VALUES(audience),
  is_active    = 1;

-- ---------------------------------------------------------------------------
-- 2. Customer launch templates (24 high-priority).
--    Inserted with the renderer's inner-content HTML; the shell is added at send time.
-- ---------------------------------------------------------------------------
INSERT INTO email_templates
  (template_key, email_name, department_id, subject_line, preview_text,
   body_html, body_text, primary_button_label, primary_button_url_template,
   dynamic_fields, audience, is_required, is_unsubscribable, unsubscribe_group, restricted_data)
VALUES
  ('customer.welcome.verify_email',
   'Welcome / Verify Email',
   (SELECT id FROM email_departments WHERE code='welcome'),
   'Verify your ReliCheck account',
   'One quick step to activate your account.',
   '<p>Hi {{first_name}},</p><p>Welcome to ReliCheck. Please confirm this email address so we can finish setting up your account.</p><p>The link below is valid for 24 hours.</p>',
   'Hi {{first_name}},\n\nWelcome to ReliCheck. Please confirm this email address so we can finish setting up your account.\n\nThe link below is valid for 24 hours.\n\n{{button_url}}\n\nIf you did not create a ReliCheck account, you can ignore this message.',
   'Verify email', '{{site_url}}/verify.html?token={{verify_token}}',
   JSON_ARRAY('first_name','verify_token'), 'customer', 1, 0, NULL, 0),

  ('customer.welcome.account_confirmed',
   'Account Confirmed',
   (SELECT id FROM email_departments WHERE code='welcome'),
   'Your ReliCheck account is ready',
   'You are all set. Sign in and create your first survey.',
   '<p>Hi {{first_name}},</p><p>Your email is verified and your ReliCheck account is active.</p><p>Sign in any time to build a survey, invite respondents, and see results in your dashboard.</p>',
   'Hi {{first_name}},\n\nYour email is verified and your ReliCheck account is active.\n\nSign in any time to build a survey, invite respondents, and see results in your dashboard.\n\n{{button_url}}',
   'Open my dashboard', '{{site_url}}/dashboard.html',
   JSON_ARRAY('first_name'), 'customer', 1, 0, NULL, 0),

  ('customer.support.password_reset',
   'Password Reset',
   (SELECT id FROM email_departments WHERE code='support'),
   'Reset your ReliCheck password',
   'Use the link below to set a new password.',
   '<p>Hi {{first_name}},</p><p>We received a request to reset the password for {{email}}. The link below expires in 30 minutes.</p>',
   'Hi {{first_name}},\n\nWe received a request to reset the password for {{email}}. The link below expires in 30 minutes.\n\n{{button_url}}\n\nIf you did not request this, you can ignore this message and your password will stay the same.',
   'Reset password', '{{site_url}}/reset.html?token={{reset_token}}',
   JSON_ARRAY('first_name','email','reset_token'), 'customer', 1, 0, NULL, 0),

  ('customer.support.password_changed',
   'Password Changed',
   (SELECT id FROM email_departments WHERE code='support'),
   'Your password was changed',
   'This is a confirmation of recent account activity.',
   '<p>Hi {{first_name}},</p><p>The password for your ReliCheck account was changed on {{changed_at}} from {{ip_address}}.</p><p>If this was you, no further action is needed. If not, secure your account right away.</p>',
   'Hi {{first_name}},\n\nThe password for your ReliCheck account was changed on {{changed_at}} from {{ip_address}}.\n\nIf this was you, no further action is needed. If not, secure your account right away.\n\n{{button_url}}',
   'Secure my account', '{{site_url}}/account/security.html',
   JSON_ARRAY('first_name','changed_at','ip_address'), 'customer', 1, 0, NULL, 0),

  ('customer.privacy.new_login_alert',
   'New Login Alert',
   (SELECT id FROM email_departments WHERE code='privacy'),
   'New sign-in to your ReliCheck account',
   'We noticed a sign-in from a new device or location.',
   '<p>Hi {{first_name}},</p><p>We saw a new sign-in to your ReliCheck account.</p><p><strong>Device:</strong> {{device}}<br><strong>Location:</strong> {{approximate_location}}<br><strong>Time:</strong> {{login_at}}</p><p>If this was you, you can ignore this message. If not, secure your account.</p>',
   'Hi {{first_name}},\n\nWe saw a new sign-in to your ReliCheck account.\n\nDevice: {{device}}\nLocation: {{approximate_location}}\nTime: {{login_at}}\n\nIf this was you, you can ignore this message. If not, secure your account.\n\n{{button_url}}',
   'Review activity', '{{site_url}}/account/security.html',
   JSON_ARRAY('first_name','device','approximate_location','login_at'), 'customer', 1, 0, NULL, 0),

  ('customer.services.first_survey_created',
   'First Survey Created',
   (SELECT id FROM email_departments WHERE code='services'),
   'Your first survey is ready to build',
   'Add questions, set distribution, and launch when ready.',
   '<p>Hi {{first_name}},</p><p>You have created your first survey, <strong>{{survey_name}}</strong>. Add the rest of your questions, choose how respondents will receive it, and launch when ready.</p>',
   'Hi {{first_name}},\n\nYou have created your first survey, {{survey_name}}. Add the rest of your questions, choose how respondents will receive it, and launch when ready.\n\n{{button_url}}',
   'Continue building', '{{site_url}}/survey-edit.html?id={{survey_id}}',
   JSON_ARRAY('first_name','survey_name','survey_id'), 'customer', 1, 0, NULL, 0),

  ('customer.services.survey_is_live',
   'Survey Is Live',
   (SELECT id FROM email_departments WHERE code='services'),
   '{{survey_name}} is live',
   'Share the link below to start collecting responses.',
   '<p>Hi {{first_name}},</p><p><strong>{{survey_name}}</strong> is live. Share the link with your respondents.</p><p style="word-break:break-all;background:#f4f5fb;padding:10px 12px;border-radius:6px;"><a href="{{public_survey_link}}">{{public_survey_link}}</a></p><p>Track responses any time from your dashboard.</p>',
   'Hi {{first_name}},\n\n{{survey_name}} is live. Share the link with your respondents.\n\n{{public_survey_link}}\n\nTrack responses any time from your dashboard.\n\n{{button_url}}',
   'Open survey', '{{site_url}}/survey.html?id={{survey_id}}',
   JSON_ARRAY('first_name','survey_name','survey_id','public_survey_link'), 'customer', 1, 0, NULL, 0),

  ('customer.services.survey_closed',
   'Survey Closed',
   (SELECT id FROM email_departments WHERE code='services'),
   '{{survey_name}} is closed',
   'Your survey is no longer accepting responses.',
   '<p>Hi {{first_name}},</p><p><strong>{{survey_name}}</strong> closed on {{closed_at}} with {{response_count}} total responses.</p><p>You can review the results or generate a report any time.</p>',
   'Hi {{first_name}},\n\n{{survey_name}} closed on {{closed_at}} with {{response_count}} total responses.\n\nYou can review the results or generate a report any time.\n\n{{button_url}}',
   'View results', '{{site_url}}/survey-results.html?id={{survey_id}}',
   JSON_ARRAY('first_name','survey_name','survey_id','closed_at','response_count'), 'customer', 1, 0, NULL, 0),

  ('customer.services.report_ready',
   'Report Ready',
   (SELECT id FROM email_departments WHERE code='services'),
   'Your report for {{survey_name}} is ready',
   'Open your report to review the findings.',
   '<p>Hi {{first_name}},</p><p>Your report for <strong>{{survey_name}}</strong> is ready.</p>',
   'Hi {{first_name}},\n\nYour report for {{survey_name}} is ready.\n\n{{button_url}}',
   'Open report', '{{site_url}}/survey-report.html?id={{survey_id}}',
   JSON_ARRAY('first_name','survey_name','survey_id'), 'customer', 1, 0, NULL, 0),

  ('customer.services.ai_insights_ready',
   'AI Insights Ready',
   (SELECT id FROM email_departments WHERE code='services'),
   'AI insights are ready for {{survey_name}}',
   'Open your dashboard to review the analysis.',
   '<p>Hi {{first_name}},</p><p>Your AI-assisted insights for <strong>{{survey_name}}</strong> are ready in your dashboard.</p>',
   'Hi {{first_name}},\n\nYour AI-assisted insights for {{survey_name}} are ready in your dashboard.\n\n{{button_url}}',
   'View insights', '{{site_url}}/survey-insights.html?id={{survey_id}}',
   JSON_ARRAY('first_name','survey_name','survey_id'), 'customer', 1, 0, NULL, 0),

  ('customer.membership.trial_started',
   'Trial Started',
   (SELECT id FROM email_departments WHERE code='membership'),
   'Your ReliCheck trial has started',
   'You have full access for the next {{trial_days}} days.',
   '<p>Hi {{first_name}},</p><p>Your free ReliCheck trial is now active. You have full access to <strong>{{plan_name}}</strong> until {{trial_end_date}}.</p>',
   'Hi {{first_name}},\n\nYour free ReliCheck trial is now active. You have full access to {{plan_name}} until {{trial_end_date}}.\n\n{{button_url}}',
   'Open dashboard', '{{site_url}}/dashboard.html',
   JSON_ARRAY('first_name','plan_name','trial_days','trial_end_date'), 'customer', 1, 0, NULL, 0),

  ('customer.membership.trial_ending_soon',
   'Trial Ending Soon',
   (SELECT id FROM email_departments WHERE code='membership'),
   'Your trial ends in 2 days',
   'Choose a plan to keep your data and projects.',
   '<p>Hi {{first_name}},</p><p>Your ReliCheck trial ends on {{trial_end_date}}. To keep your projects, results, and account access, choose a plan before then.</p>',
   'Hi {{first_name}},\n\nYour ReliCheck trial ends on {{trial_end_date}}. To keep your projects, results, and account access, choose a plan before then.\n\n{{button_url}}',
   'Choose a plan', '{{site_url}}/pricing.html',
   JSON_ARRAY('first_name','trial_end_date'), 'customer', 1, 0, NULL, 0),

  ('customer.membership.trial_expired',
   'Trial Expired',
   (SELECT id FROM email_departments WHERE code='membership'),
   'Your trial has ended',
   'Reactivate any time to regain full access.',
   '<p>Hi {{first_name}},</p><p>Your ReliCheck trial ended on {{trial_end_date}}. Your projects are saved. Choose a plan to restore full access.</p>',
   'Hi {{first_name}},\n\nYour ReliCheck trial ended on {{trial_end_date}}. Your projects are saved. Choose a plan to restore full access.\n\n{{button_url}}',
   'Choose a plan', '{{site_url}}/pricing.html',
   JSON_ARRAY('first_name','trial_end_date'), 'customer', 1, 0, NULL, 0),

  ('customer.membership.upgraded',
   'Membership Upgraded',
   (SELECT id FROM email_departments WHERE code='membership'),
   'Your plan has been upgraded',
   'New features and limits are now available.',
   '<p>Hi {{first_name}},</p><p>Your account is now on the <strong>{{plan_name}}</strong> plan, effective {{effective_date}}.</p>',
   'Hi {{first_name}},\n\nYour account is now on the {{plan_name}} plan, effective {{effective_date}}.\n\n{{button_url}}',
   'Open billing', '{{site_url}}/account/billing.html',
   JSON_ARRAY('first_name','plan_name','effective_date'), 'customer', 1, 0, NULL, 0),

  ('customer.membership.changed',
   'Membership Changed',
   (SELECT id FROM email_departments WHERE code='membership'),
   'Your plan has been updated',
   'Review your updated access and limits.',
   '<p>Hi {{first_name}},</p><p>Your plan was changed to <strong>{{plan_name}}</strong>, effective {{effective_date}}. Updated access and usage limits are reflected in your billing summary.</p>',
   'Hi {{first_name}},\n\nYour plan was changed to {{plan_name}}, effective {{effective_date}}. Updated access and usage limits are reflected in your billing summary.\n\n{{button_url}}',
   'Open billing', '{{site_url}}/account/billing.html',
   JSON_ARRAY('first_name','plan_name','effective_date'), 'customer', 1, 0, NULL, 0),

  ('customer.membership.cancellation_confirmed',
   'Cancellation Confirmation',
   (SELECT id FROM email_departments WHERE code='membership'),
   'Your ReliCheck subscription has been cancelled',
   'Access continues until {{access_end_date}}.',
   '<p>Hi {{first_name}},</p><p>Your subscription was cancelled on {{cancelled_at}}. You will keep access to your current plan through {{access_end_date}}.</p><p>You can reactivate any time before that date with one click.</p>',
   'Hi {{first_name}},\n\nYour subscription was cancelled on {{cancelled_at}}. You will keep access to your current plan through {{access_end_date}}.\n\nYou can reactivate any time before that date with one click.\n\n{{button_url}}',
   'Reactivate', '{{site_url}}/account/billing.html',
   JSON_ARRAY('first_name','cancelled_at','access_end_date'), 'customer', 1, 0, NULL, 0),

  ('customer.billing.payment_receipt',
   'Payment Receipt',
   (SELECT id FROM email_departments WHERE code='billing'),
   'Receipt for your ReliCheck payment',
   '{{amount}} charged on {{charge_date}}.',
   '<p>Hi {{first_name}},</p><p>Thank you for your payment.</p><p><strong>Amount:</strong> {{amount}}<br><strong>Date:</strong> {{charge_date}}<br><strong>Plan:</strong> {{plan_name}}<br><strong>Invoice:</strong> {{invoice_number}}</p>',
   'Hi {{first_name}},\n\nThank you for your payment.\n\nAmount: {{amount}}\nDate: {{charge_date}}\nPlan: {{plan_name}}\nInvoice: {{invoice_number}}\n\n{{button_url}}',
   'View invoice', '{{site_url}}/account/invoices.html?id={{invoice_id}}',
   JSON_ARRAY('first_name','amount','charge_date','plan_name','invoice_number','invoice_id'), 'customer', 1, 0, NULL, 0),

  ('customer.billing.payment_failed',
   'Payment Failed',
   (SELECT id FROM email_departments WHERE code='billing'),
   'We could not process your payment',
   'Update your payment method to keep your account active.',
   '<p>Hi {{first_name}},</p><p>Your most recent payment of <strong>{{amount}}</strong> on {{attempted_at}} did not go through. Please update your payment method so we can retry the charge.</p>',
   'Hi {{first_name}},\n\nYour most recent payment of {{amount}} on {{attempted_at}} did not go through. Please update your payment method so we can retry the charge.\n\n{{button_url}}',
   'Update payment method', '{{site_url}}/account/billing.html',
   JSON_ARRAY('first_name','amount','attempted_at'), 'customer', 1, 0, NULL, 0),

  ('customer.billing.refund_confirmed',
   'Refund Confirmation',
   (SELECT id FROM email_departments WHERE code='billing'),
   'Your refund has been issued',
   '{{amount}} returned to your original payment method.',
   '<p>Hi {{first_name}},</p><p>A refund of <strong>{{amount}}</strong> for invoice {{invoice_number}} was issued on {{refund_date}}. Funds typically appear in 5 to 10 business days.</p>',
   'Hi {{first_name}},\n\nA refund of {{amount}} for invoice {{invoice_number}} was issued on {{refund_date}}. Funds typically appear in 5 to 10 business days.\n\n{{button_url}}',
   'View invoice', '{{site_url}}/account/invoices.html?id={{invoice_id}}',
   JSON_ARRAY('first_name','amount','invoice_number','refund_date','invoice_id'), 'customer', 1, 0, NULL, 0),

  ('customer.support.ticket_received',
   'Support Ticket Received',
   (SELECT id FROM email_departments WHERE code='support'),
   'Ticket {{ticket_number}}: we got your message',
   'A team member will reply within {{sla_hours}} hours.',
   '<p>Hi {{first_name}},</p><p>Thanks for reaching out. Your ticket is <strong>{{ticket_number}}</strong>, and a member of our team will reply within {{sla_hours}} hours.</p><p><strong>Subject:</strong> {{ticket_subject}}</p>',
   'Hi {{first_name}},\n\nThanks for reaching out. Your ticket is {{ticket_number}}, and a member of our team will reply within {{sla_hours}} hours.\n\nSubject: {{ticket_subject}}\n\n{{button_url}}',
   'View ticket', '{{site_url}}/support/ticket.html?id={{ticket_id}}',
   JSON_ARRAY('first_name','ticket_number','ticket_id','ticket_subject','sla_hours'), 'customer', 1, 0, NULL, 0),

  ('customer.support.ticket_response',
   'Support Response',
   (SELECT id FROM email_departments WHERE code='support'),
   'New reply on ticket {{ticket_number}}',
   '{{agent_first_name}} responded to your request.',
   '<p>Hi {{first_name}},</p><p>{{agent_first_name}} from ReliCheck Support replied to your ticket <strong>{{ticket_number}}</strong>.</p>',
   'Hi {{first_name}},\n\n{{agent_first_name}} from ReliCheck Support replied to your ticket {{ticket_number}}.\n\n{{button_url}}',
   'View reply', '{{site_url}}/support/ticket.html?id={{ticket_id}}',
   JSON_ARRAY('first_name','agent_first_name','ticket_number','ticket_id'), 'customer', 1, 0, NULL, 0),

  ('customer.support.ticket_closed',
   'Support Ticket Closed',
   (SELECT id FROM email_departments WHERE code='support'),
   'Ticket {{ticket_number}} is closed',
   'We are glad we could help. Reopen any time.',
   '<p>Hi {{first_name}},</p><p>Your ticket <strong>{{ticket_number}}</strong> is now closed. If you need anything else, reply to this email and we will reopen it.</p>',
   'Hi {{first_name}},\n\nYour ticket {{ticket_number}} is now closed. If you need anything else, reply to this email and we will reopen it.\n\n{{button_url}}',
   'View ticket', '{{site_url}}/support/ticket.html?id={{ticket_id}}',
   JSON_ARRAY('first_name','ticket_number','ticket_id'), 'customer', 1, 0, NULL, 0),

  ('customer.privacy.policy_update',
   'Privacy Policy Update',
   (SELECT id FROM email_departments WHERE code='privacy'),
   'We have updated our privacy policy',
   'New policy takes effect on {{effective_date}}.',
   '<p>Hi {{first_name}},</p><p>We have updated the ReliCheck privacy policy. The new policy takes effect on {{effective_date}}. A short summary of the changes is on our site.</p>',
   'Hi {{first_name}},\n\nWe have updated the ReliCheck privacy policy. The new policy takes effect on {{effective_date}}. A short summary of the changes is on our site.\n\n{{button_url}}',
   'Read the policy', '{{site_url}}/privacy.html',
   JSON_ARRAY('first_name','effective_date'), 'customer', 1, 0, NULL, 0),

  ('customer.privacy.data_export_ready',
   'Data Export Ready',
   (SELECT id FROM email_departments WHERE code='privacy'),
   'Your data export is ready',
   'The download link is valid for 7 days.',
   '<p>Hi {{first_name}},</p><p>The data export you requested on {{requested_at}} is ready. The download link is valid for 7 days.</p>',
   'Hi {{first_name}},\n\nThe data export you requested on {{requested_at}} is ready. The download link is valid for 7 days.\n\n{{button_url}}',
   'Download export', '{{site_url}}/account/exports.html?id={{export_id}}',
   JSON_ARRAY('first_name','requested_at','export_id'), 'customer', 1, 0, NULL, 0),

  ('customer.terms.update',
   'Terms Update',
   (SELECT id FROM email_departments WHERE code='terms'),
   'Updates to our Terms of Service',
   'New terms take effect on {{effective_date}}.',
   '<p>Hi {{first_name}},</p><p>We have updated the ReliCheck Terms of Service. The new terms take effect on {{effective_date}}. Continued use of the service after that date constitutes acceptance.</p>',
   'Hi {{first_name}},\n\nWe have updated the ReliCheck Terms of Service. The new terms take effect on {{effective_date}}. Continued use of the service after that date constitutes acceptance.\n\n{{button_url}}',
   'Read the new terms', '{{site_url}}/terms.html',
   JSON_ARRAY('first_name','effective_date'), 'customer', 1, 0, NULL, 0)
ON DUPLICATE KEY UPDATE
  email_name           = VALUES(email_name),
  subject_line         = VALUES(subject_line),
  preview_text         = VALUES(preview_text),
  body_html            = VALUES(body_html),
  body_text            = VALUES(body_text),
  primary_button_label = VALUES(primary_button_label),
  primary_button_url_template = VALUES(primary_button_url_template),
  dynamic_fields       = VALUES(dynamic_fields),
  is_required          = VALUES(is_required),
  is_unsubscribable    = VALUES(is_unsubscribable),
  unsubscribe_group    = VALUES(unsubscribe_group),
  restricted_data      = VALUES(restricted_data),
  is_active            = 1;

-- ---------------------------------------------------------------------------
-- 3. Employee/admin launch templates (19).
-- ---------------------------------------------------------------------------
INSERT INTO email_templates
  (template_key, email_name, department_id, subject_line, preview_text,
   body_html, body_text, primary_button_label, primary_button_url_template,
   dynamic_fields, audience, is_required, is_unsubscribable, unsubscribe_group, restricted_data)
VALUES
  ('employee.hr.admin_invite',
   'Admin Panel Invitation',
   (SELECT id FROM email_departments WHERE code='hr'),
   'You have been invited to the ReliCheck admin panel',
   'Accept your invitation to get started.',
   '<p>Hi {{first_name}},</p><p>You have been invited to the ReliCheck admin panel by <strong>{{inviter_name}}</strong> as a <strong>{{role_name}}</strong> in the <strong>{{department_name}}</strong> department.</p><p>This link expires in 72 hours.</p>',
   'Hi {{first_name}},\n\nYou have been invited to the ReliCheck admin panel by {{inviter_name}} as a {{role_name}} in the {{department_name}} department.\n\n{{button_url}}\n\nThis link expires in 72 hours.',
   'Accept invitation', '{{site_url}}/admin/accept-invite.html?token={{invite_token}}',
   JSON_ARRAY('first_name','inviter_name','role_name','department_name','invite_token'), 'employee', 1, 0, NULL, 0),

  ('employee.hr.account_confirmed',
   'Employee Account Confirmed',
   (SELECT id FROM email_departments WHERE code='hr'),
   'Your ReliCheck admin account is active',
   'You can now sign in to the admin panel.',
   '<p>Hi {{first_name}},</p><p>Your admin account is active with the role <strong>{{role_name}}</strong>. Sign in to the admin panel any time.</p>',
   'Hi {{first_name}},\n\nYour admin account is active with the role {{role_name}}. Sign in to the admin panel any time.\n\n{{button_url}}',
   'Open admin panel', '{{site_url}}/admin.html',
   JSON_ARRAY('first_name','role_name'), 'employee', 1, 0, NULL, 0),

  ('employee.hr.role_changed',
   'Employee Role Changed',
   (SELECT id FROM email_departments WHERE code='hr'),
   'Your role has been updated',
   'Your role and access in the admin panel have changed.',
   '<p>Hi {{first_name}},</p><p>Your role was changed from <strong>{{previous_role}}</strong> to <strong>{{new_role}}</strong>, effective {{effective_date}}.</p>',
   'Hi {{first_name}},\n\nYour role was changed from {{previous_role}} to {{new_role}}, effective {{effective_date}}.\n\n{{button_url}}',
   'Open profile', '{{site_url}}/admin/profile.html',
   JSON_ARRAY('first_name','previous_role','new_role','effective_date'), 'employee', 1, 0, NULL, 0),

  ('employee.hr.access_removed',
   'Employee Access Removed',
   (SELECT id FROM email_departments WHERE code='hr'),
   'Your ReliCheck admin access has been removed',
   'Your access to the admin panel ended on {{removed_at}}.',
   '<p>Hi {{first_name}},</p><p>Your access to the ReliCheck admin panel was removed on <strong>{{removed_at}}</strong>. If you have questions, contact <a href="mailto:{{contact_email}}">{{contact_email}}</a>.</p>',
   'Hi {{first_name}},\n\nYour access to the ReliCheck admin panel was removed on {{removed_at}}. If you have questions, contact {{contact_email}}.',
   NULL, NULL,
   JSON_ARRAY('first_name','removed_at','contact_email'), 'employee', 1, 0, NULL, 0),

  ('employee.support.new_ticket_assigned',
   'New Ticket Assigned',
   (SELECT id FROM email_departments WHERE code='support'),
   'New ticket assigned: {{ticket_number}}',
   'Ticket {{ticket_number}} is now in your queue.',
   '<p>Hi {{agent_first_name}},</p><p>Ticket <strong>{{ticket_number}}</strong> has been assigned to you.</p><p><strong>Customer:</strong> {{customer_account_name}}<br><strong>Subject:</strong> {{ticket_subject}}<br><strong>Priority:</strong> {{priority}}<br><strong>SLA due:</strong> {{sla_due}}</p>',
   'Hi {{agent_first_name}},\n\nTicket {{ticket_number}} has been assigned to you.\n\nCustomer: {{customer_account_name}}\nSubject: {{ticket_subject}}\nPriority: {{priority}}\nSLA due: {{sla_due}}\n\n{{button_url}}',
   'Open ticket', '{{site_url}}/admin/ticket.html?id={{ticket_id}}',
   JSON_ARRAY('agent_first_name','ticket_number','ticket_id','customer_account_name','ticket_subject','priority','sla_due'), 'employee', 1, 0, NULL, 0),

  ('employee.support.customer_reply',
   'Customer Reply Received',
   (SELECT id FROM email_departments WHERE code='support'),
   'Customer reply on ticket {{ticket_number}}',
   'A new customer reply is waiting for you.',
   '<p>Hi {{agent_first_name}},</p><p>{{customer_account_name}} replied on ticket <strong>{{ticket_number}}</strong>. Open the ticket in the admin panel to view the reply.</p>',
   'Hi {{agent_first_name}},\n\n{{customer_account_name}} replied on ticket {{ticket_number}}. Open the ticket in the admin panel to view the reply.\n\n{{button_url}}',
   'Open ticket', '{{site_url}}/admin/ticket.html?id={{ticket_id}}',
   JSON_ARRAY('agent_first_name','ticket_number','ticket_id','customer_account_name'), 'employee', 1, 0, NULL, 0),

  ('employee.support.ticket_overdue',
   'Ticket Overdue',
   (SELECT id FROM email_departments WHERE code='support'),
   'Overdue: ticket {{ticket_number}}',
   'SLA breached by {{overdue_by}}.',
   '<p>Hi {{agent_first_name}},</p><p>Ticket <strong>{{ticket_number}}</strong> has breached its SLA (due {{sla_due}}, overdue by {{overdue_by}}).</p>',
   'Hi {{agent_first_name}},\n\nTicket {{ticket_number}} has breached its SLA (due {{sla_due}}, overdue by {{overdue_by}}).\n\n{{button_url}}',
   'Open ticket', '{{site_url}}/admin/ticket.html?id={{ticket_id}}',
   JSON_ARRAY('agent_first_name','ticket_number','ticket_id','sla_due','overdue_by'), 'employee', 1, 0, NULL, 0),

  ('employee.support.ticket_escalated',
   'Ticket Escalated',
   (SELECT id FROM email_departments WHERE code='support'),
   'Escalated: ticket {{ticket_number}}',
   'Escalation reason: {{reason}}',
   '<p>Hi {{supervisor_first_name}},</p><p>Ticket <strong>{{ticket_number}}</strong> was escalated by {{escalated_by}}.</p><p><strong>Reason:</strong> {{reason}}</p>',
   'Hi {{supervisor_first_name}},\n\nTicket {{ticket_number}} was escalated by {{escalated_by}}.\n\nReason: {{reason}}\n\n{{button_url}}',
   'Open ticket', '{{site_url}}/admin/ticket.html?id={{ticket_id}}',
   JSON_ARRAY('supervisor_first_name','ticket_number','ticket_id','escalated_by','reason'), 'employee', 1, 0, NULL, 0),

  ('employee.membership.plan_manually_changed',
   'Membership Manually Changed',
   (SELECT id FROM email_departments WHERE code='membership'),
   'Plan manually changed for {{customer_account_name}}',
   '{{actor_name}} updated the plan.',
   '<p>{{actor_name}} changed the plan for <strong>{{customer_account_name}}</strong> from <strong>{{prior_plan}}</strong> to <strong>{{new_plan}}</strong>, effective {{effective_date}}.</p>',
   '{{actor_name}} changed the plan for {{customer_account_name}} from {{prior_plan}} to {{new_plan}}, effective {{effective_date}}.\n\n{{button_url}}',
   'Open customer', '{{site_url}}/admin/customer.html?id={{customer_id}}',
   JSON_ARRAY('actor_name','customer_account_name','customer_id','prior_plan','new_plan','effective_date'), 'employee', 1, 0, NULL, 0),

  ('employee.membership.promo_created',
   'Promo Code Created',
   (SELECT id FROM email_departments WHERE code='membership'),
   'Promo code created: {{promo_code}}',
   '{{discount_label}}, valid {{valid_from}} to {{valid_to}}.',
   '<p>Promo code <strong>{{promo_code}}</strong> was created by {{created_by}}.</p><p><strong>Discount:</strong> {{discount_label}}<br><strong>Valid:</strong> {{valid_from}} to {{valid_to}}</p>',
   'Promo code {{promo_code}} was created by {{created_by}}.\n\nDiscount: {{discount_label}}\nValid: {{valid_from}} to {{valid_to}}\n\n{{button_url}}',
   'Open promo', '{{site_url}}/admin/promo.html?code={{promo_code}}',
   JSON_ARRAY('promo_code','discount_label','valid_from','valid_to','created_by'), 'employee', 1, 0, NULL, 0),

  ('employee.membership.promo_edited',
   'Promo Code Edited',
   (SELECT id FROM email_departments WHERE code='membership'),
   'Promo code updated: {{promo_code}}',
   '{{edited_by}} edited the promo code.',
   '<p>Promo code <strong>{{promo_code}}</strong> was edited by {{edited_by}}.</p><p><strong>Changes:</strong> {{changes_summary}}</p>',
   'Promo code {{promo_code}} was edited by {{edited_by}}.\n\nChanges: {{changes_summary}}\n\n{{button_url}}',
   'Open promo', '{{site_url}}/admin/promo.html?code={{promo_code}}',
   JSON_ARRAY('promo_code','changes_summary','edited_by'), 'employee', 1, 0, NULL, 0),

  ('employee.billing.payment_issue_alert',
   'Payment Issue Alert',
   (SELECT id FROM email_departments WHERE code='billing'),
   'Payment issue: {{customer_account_name}}',
   '{{attempts}} failed attempts. Reason: {{failure_reason}}.',
   '<p>Customer <strong>{{customer_account_name}}</strong> has had {{attempts}} failed payment attempts.</p><p><strong>Reason:</strong> {{failure_reason}}</p>',
   'Customer {{customer_account_name}} has had {{attempts}} failed payment attempts.\n\nReason: {{failure_reason}}\n\n{{button_url}}',
   'Open customer billing', '{{site_url}}/admin/customer.html?id={{customer_id}}#billing',
   JSON_ARRAY('customer_account_name','customer_id','attempts','failure_reason'), 'employee', 1, 0, NULL, 0),

  ('employee.billing.refund_processed',
   'Refund Processed',
   (SELECT id FROM email_departments WHERE code='billing'),
   'Refund processed: {{customer_account_name}}',
   '{{amount}} on invoice {{invoice_number}}.',
   '<p>{{processed_by}} processed a refund of <strong>{{amount}}</strong> for {{customer_account_name}} on invoice <strong>{{invoice_number}}</strong>.</p>',
   '{{processed_by}} processed a refund of {{amount}} for {{customer_account_name}} on invoice {{invoice_number}}.\n\n{{button_url}}',
   'Open customer billing', '{{site_url}}/admin/customer.html?id={{customer_id}}#billing',
   JSON_ARRAY('customer_account_name','customer_id','amount','invoice_number','processed_by'), 'employee', 1, 0, NULL, 0),

  ('employee.services.task_assigned',
   'Service Task Assigned',
   (SELECT id FROM email_departments WHERE code='services'),
   'New service task: {{task_type}} for {{customer_account_name}}',
   'Task assigned, SLA due {{sla_due}}.',
   '<p>Hi {{rep_first_name}},</p><p>A new service task is assigned to you.</p><p><strong>Type:</strong> {{task_type}}<br><strong>Customer:</strong> {{customer_account_name}}<br><strong>SLA due:</strong> {{sla_due}}</p>',
   'Hi {{rep_first_name}},\n\nA new service task is assigned to you.\n\nType: {{task_type}}\nCustomer: {{customer_account_name}}\nSLA due: {{sla_due}}\n\n{{button_url}}',
   'Open task', '{{site_url}}/admin/service-task.html?id={{task_id}}',
   JSON_ARRAY('rep_first_name','task_type','customer_account_name','customer_id','sla_due','task_id'), 'employee', 1, 0, NULL, 0),

  ('employee.privacy.review_needed',
   'Privacy Review Needed',
   (SELECT id FROM email_departments WHERE code='privacy'),
   'Privacy review needed: {{case_reference}}',
   '{{issue_type}}, due {{due_date}}.',
   '<p>Hi {{privacy_officer_first_name}},</p><p>A privacy case needs your review.</p><p><strong>Reference:</strong> {{case_reference}}<br><strong>Type:</strong> {{issue_type}}<br><strong>Due:</strong> {{due_date}}</p>',
   'Hi {{privacy_officer_first_name}},\n\nA privacy case needs your review.\n\nReference: {{case_reference}}\nType: {{issue_type}}\nDue: {{due_date}}\n\n{{button_url}}',
   'Open case', '{{site_url}}/admin/privacy-case.html?id={{case_id}}',
   JSON_ARRAY('privacy_officer_first_name','case_reference','case_id','issue_type','due_date'), 'employee', 1, 0, NULL, 0),

  ('employee.legal.review_needed',
   'Legal Review Needed',
   (SELECT id FROM email_departments WHERE code='legal'),
   'Legal review needed: {{case_reference}}',
   '{{issue_type}}, urgency {{urgency}}.',
   '<p>Hi {{legal_owner_first_name}},</p><p>A legal case needs your review.</p><p><strong>Reference:</strong> {{case_reference}}<br><strong>Type:</strong> {{issue_type}}<br><strong>Urgency:</strong> {{urgency}}</p>',
   'Hi {{legal_owner_first_name}},\n\nA legal case needs your review.\n\nReference: {{case_reference}}\nType: {{issue_type}}\nUrgency: {{urgency}}\n\n{{button_url}}',
   'Open case', '{{site_url}}/admin/legal-case.html?id={{case_id}}',
   JSON_ARRAY('legal_owner_first_name','case_reference','case_id','issue_type','urgency'), 'employee', 1, 0, NULL, 0),

  ('employee.sales.demo_request',
   'Demo Request',
   (SELECT id FROM email_departments WHERE code='sales'),
   'New demo request from {{lead_organization}}',
   '{{lead_name}}, {{lead_segment}}.',
   '<p>Hi {{rep_first_name}},</p><p>A new demo request was submitted.</p><p><strong>Lead:</strong> {{lead_name}}<br><strong>Organization:</strong> {{lead_organization}}<br><strong>Segment:</strong> {{lead_segment}}</p>',
   'Hi {{rep_first_name}},\n\nA new demo request was submitted.\n\nLead: {{lead_name}}\nOrganization: {{lead_organization}}\nSegment: {{lead_segment}}\n\n{{button_url}}',
   'Open lead', '{{site_url}}/admin/lead.html?id={{lead_id}}',
   JSON_ARRAY('rep_first_name','lead_name','lead_organization','lead_segment','lead_id'), 'employee', 1, 0, NULL, 0),

  ('employee.sales.new_lead',
   'New Lead',
   (SELECT id FROM email_departments WHERE code='sales'),
   'New lead: {{lead_organization}}',
   'Source: {{source}}.',
   '<p>Hi {{rep_first_name}},</p><p>A new lead arrived.</p><p><strong>Lead:</strong> {{lead_name}}<br><strong>Organization:</strong> {{lead_organization}}<br><strong>Source:</strong> {{source}}</p>',
   'Hi {{rep_first_name}},\n\nA new lead arrived.\n\nLead: {{lead_name}}\nOrganization: {{lead_organization}}\nSource: {{source}}\n\n{{button_url}}',
   'Open lead', '{{site_url}}/admin/lead.html?id={{lead_id}}',
   JSON_ARRAY('rep_first_name','lead_name','lead_organization','source','lead_id'), 'employee', 1, 0, NULL, 0),

  ('employee.support.system_alert',
   'System Alert',
   (SELECT id FROM email_departments WHERE code='support'),
   'System alert: {{alert_label}}',
   'Severity {{severity}} on {{component}}.',
   '<p>Hi {{oncall_first_name}},</p><p>A system alert has fired.</p><p><strong>Alert:</strong> {{alert_label}}<br><strong>Severity:</strong> {{severity}}<br><strong>Component:</strong> {{component}}</p>',
   'Hi {{oncall_first_name}},\n\nA system alert has fired.\n\nAlert: {{alert_label}}\nSeverity: {{severity}}\nComponent: {{component}}\n\n{{button_url}}',
   'Open dashboard', '{{dashboard_url}}',
   JSON_ARRAY('oncall_first_name','alert_label','severity','component','dashboard_url'), 'employee', 1, 0, NULL, 0)
ON DUPLICATE KEY UPDATE
  email_name           = VALUES(email_name),
  subject_line         = VALUES(subject_line),
  preview_text         = VALUES(preview_text),
  body_html            = VALUES(body_html),
  body_text            = VALUES(body_text),
  primary_button_label = VALUES(primary_button_label),
  primary_button_url_template = VALUES(primary_button_url_template),
  dynamic_fields       = VALUES(dynamic_fields),
  is_required          = VALUES(is_required),
  is_unsubscribable    = VALUES(is_unsubscribable),
  unsubscribe_group    = VALUES(unsubscribe_group),
  restricted_data      = VALUES(restricted_data),
  is_active            = 1;

-- ---------------------------------------------------------------------------
-- 4. Snapshot every active template into email_template_versions as v1.
--    (Idempotent thanks to the UNIQUE constraint.)
-- ---------------------------------------------------------------------------
INSERT IGNORE INTO email_template_versions
  (template_id, version_number, subject_line, preview_text, body_html, body_text,
   primary_button_label, primary_button_url_template, dynamic_fields,
   edited_by_user_id, change_note)
SELECT id, current_version, subject_line, preview_text, body_html, body_text,
       primary_button_label, primary_button_url_template, dynamic_fields,
       NULL, 'Initial seed (schema_phase31b)'
FROM email_templates;

-- ---------------------------------------------------------------------------
-- 5. Event bindings. Each event_key links to a customer template and/or an
--    employee template. recipient_resolver names the function in
--    api/_email_resolver.php that returns the recipient list.
-- ---------------------------------------------------------------------------
INSERT INTO email_events
  (event_key, description, customer_template_id, employee_template_id,
   recipient_resolver, dedupe_window_minutes, priority, is_required)
VALUES
  ('user.created',                'Customer created an account',
    (SELECT id FROM email_templates WHERE template_key='customer.welcome.verify_email'), NULL,
    'customer_self', 0, 'P0', 1),
  ('user.email_verified',         'Customer verified email',
    (SELECT id FROM email_templates WHERE template_key='customer.welcome.account_confirmed'), NULL,
    'customer_self', 0, 'P1', 1),
  ('password.reset_requested',    'Customer requested a password reset',
    (SELECT id FROM email_templates WHERE template_key='customer.support.password_reset'), NULL,
    'customer_self', 0, 'P0', 1),
  ('password.changed',            'Customer password was changed',
    (SELECT id FROM email_templates WHERE template_key='customer.support.password_changed'), NULL,
    'customer_self', 0, 'P0', 1),
  ('auth.new_device_or_location', 'Sign-in from new device or location',
    (SELECT id FROM email_templates WHERE template_key='customer.privacy.new_login_alert'), NULL,
    'customer_self', 60, 'P0', 1),
  ('survey.first_created',        'Customer created their first survey',
    (SELECT id FROM email_templates WHERE template_key='customer.services.first_survey_created'), NULL,
    'customer_self', 0, 'P2', 1),
  ('survey.published',            'Survey was published',
    (SELECT id FROM email_templates WHERE template_key='customer.services.survey_is_live'), NULL,
    'customer_self', 0, 'P1', 1),
  ('survey.closed',               'Survey was closed',
    (SELECT id FROM email_templates WHERE template_key='customer.services.survey_closed'), NULL,
    'customer_self', 0, 'P1', 1),
  ('report.generated',            'Survey report was generated',
    (SELECT id FROM email_templates WHERE template_key='customer.services.report_ready'), NULL,
    'customer_self', 0, 'P1', 1),
  ('insights.generated',          'AI insights were generated',
    (SELECT id FROM email_templates WHERE template_key='customer.services.ai_insights_ready'), NULL,
    'customer_self', 0, 'P1', 1),
  ('trial.started',               'Trial began',
    (SELECT id FROM email_templates WHERE template_key='customer.membership.trial_started'), NULL,
    'customer_self', 0, 'P1', 1),
  ('trial.ending_soon',           'Trial ends in 2 days',
    (SELECT id FROM email_templates WHERE template_key='customer.membership.trial_ending_soon'), NULL,
    'customer_self', 1440, 'P1', 1),
  ('trial.expired',               'Trial expired',
    (SELECT id FROM email_templates WHERE template_key='customer.membership.trial_expired'), NULL,
    'customer_self', 0, 'P1', 1),
  ('membership.upgraded',         'Customer upgraded plan',
    (SELECT id FROM email_templates WHERE template_key='customer.membership.upgraded'),
    (SELECT id FROM email_templates WHERE template_key='employee.membership.plan_manually_changed'),
    'customer_plus_membership_ops', 0, 'P1', 1),
  ('membership.changed',          'Customer plan changed',
    (SELECT id FROM email_templates WHERE template_key='customer.membership.changed'), NULL,
    'customer_self', 0, 'P1', 1),
  ('membership.cancelled',        'Customer cancelled subscription',
    (SELECT id FROM email_templates WHERE template_key='customer.membership.cancellation_confirmed'), NULL,
    'customer_self', 0, 'P1', 1),
  ('billing.charge.succeeded',    'Customer payment succeeded',
    (SELECT id FROM email_templates WHERE template_key='customer.billing.payment_receipt'), NULL,
    'customer_self', 0, 'P0', 1),
  ('billing.charge.failed',       'Customer payment failed',
    (SELECT id FROM email_templates WHERE template_key='customer.billing.payment_failed'),
    (SELECT id FROM email_templates WHERE template_key='employee.billing.payment_issue_alert'),
    'customer_plus_billing_ops', 0, 'P0', 1),
  ('billing.refund_issued',       'Refund issued to customer',
    (SELECT id FROM email_templates WHERE template_key='customer.billing.refund_confirmed'),
    (SELECT id FROM email_templates WHERE template_key='employee.billing.refund_processed'),
    'customer_plus_billing_ops', 0, 'P1', 1),
  ('support.ticket.created',      'Customer submitted a support ticket',
    (SELECT id FROM email_templates WHERE template_key='customer.support.ticket_received'),
    (SELECT id FROM email_templates WHERE template_key='employee.support.new_ticket_assigned'),
    'customer_plus_assigned_agent', 0, 'P1', 1),
  ('support.ticket.replied_by_agent', 'Agent replied to customer',
    (SELECT id FROM email_templates WHERE template_key='customer.support.ticket_response'), NULL,
    'customer_self', 0, 'P1', 1),
  ('support.ticket.replied_by_customer', 'Customer replied to ticket',
    NULL,
    (SELECT id FROM email_templates WHERE template_key='employee.support.customer_reply'),
    'assigned_agent', 0, 'P1', 1),
  ('support.ticket.closed',       'Support ticket closed',
    (SELECT id FROM email_templates WHERE template_key='customer.support.ticket_closed'), NULL,
    'customer_self', 0, 'P1', 1),
  ('support.ticket.overdue',      'Support ticket SLA breach',
    NULL,
    (SELECT id FROM email_templates WHERE template_key='employee.support.ticket_overdue'),
    'assigned_agent_plus_supervisor', 60, 'P1', 1),
  ('support.ticket.escalated',    'Support ticket escalated',
    NULL,
    (SELECT id FROM email_templates WHERE template_key='employee.support.ticket_escalated'),
    'supervisor_plus_owner', 0, 'P0', 1),
  ('privacy.policy_updated',      'Privacy policy was updated',
    (SELECT id FROM email_templates WHERE template_key='customer.privacy.policy_update'), NULL,
    'all_customers', 0, 'P0', 1),
  ('privacy.export_ready',        'Customer data export is ready',
    (SELECT id FROM email_templates WHERE template_key='customer.privacy.data_export_ready'), NULL,
    'customer_self', 0, 'P1', 1),
  ('privacy.review_needed',       'Privacy issue needs review',
    NULL,
    (SELECT id FROM email_templates WHERE template_key='employee.privacy.review_needed'),
    'privacy_officers', 0, 'P0', 1),
  ('terms.updated',               'Terms of service updated',
    (SELECT id FROM email_templates WHERE template_key='customer.terms.update'), NULL,
    'all_customers', 0, 'P0', 1),
  ('legal.review_needed',         'Legal issue needs review',
    NULL,
    (SELECT id FROM email_templates WHERE template_key='employee.legal.review_needed'),
    'legal_owners', 0, 'P0', 1),
  ('hr.invite_employee',          'Admin panel invitation sent',
    NULL,
    (SELECT id FROM email_templates WHERE template_key='employee.hr.admin_invite'),
    'invited_employee', 0, 'P0', 1),
  ('hr.employee_confirmed',       'Employee account is active',
    NULL,
    (SELECT id FROM email_templates WHERE template_key='employee.hr.account_confirmed'),
    'employee_self', 0, 'P1', 1),
  ('hr.role_changed',             'Employee role changed',
    NULL,
    (SELECT id FROM email_templates WHERE template_key='employee.hr.role_changed'),
    'employee_self', 0, 'P1', 1),
  ('hr.access_removed',           'Employee access removed',
    NULL,
    (SELECT id FROM email_templates WHERE template_key='employee.hr.access_removed'),
    'employee_self', 0, 'P0', 1),
  ('membership.promo_created',    'Promo code created',
    NULL,
    (SELECT id FROM email_templates WHERE template_key='employee.membership.promo_created'),
    'membership_and_marketing', 0, 'P2', 1),
  ('membership.promo_edited',     'Promo code edited',
    NULL,
    (SELECT id FROM email_templates WHERE template_key='employee.membership.promo_edited'),
    'membership_and_marketing', 0, 'P2', 1),
  ('services.task_assigned',      'Service task assigned',
    NULL,
    (SELECT id FROM email_templates WHERE template_key='employee.services.task_assigned'),
    'assigned_services_rep', 0, 'P1', 1),
  ('sales.demo_requested',        'Customer requested a demo',
    NULL,
    (SELECT id FROM email_templates WHERE template_key='employee.sales.demo_request'),
    'sales_reps', 0, 'P1', 1),
  ('sales.lead_submitted',        'New lead submitted',
    NULL,
    (SELECT id FROM email_templates WHERE template_key='employee.sales.new_lead'),
    'sales_reps', 0, 'P1', 1),
  ('system.alert_fired',          'System alert',
    NULL,
    (SELECT id FROM email_templates WHERE template_key='employee.support.system_alert'),
    'oncall', 5, 'P0', 1)
ON DUPLICATE KEY UPDATE
  description           = VALUES(description),
  customer_template_id  = VALUES(customer_template_id),
  employee_template_id  = VALUES(employee_template_id),
  recipient_resolver    = VALUES(recipient_resolver),
  dedupe_window_minutes = VALUES(dedupe_window_minutes),
  priority              = VALUES(priority),
  is_required           = VALUES(is_required),
  is_active             = 1;

-- ---------------------------------------------------------------------------
-- Verification.
-- ---------------------------------------------------------------------------
SELECT
  (SELECT COUNT(*) FROM email_departments)        AS departments_seeded,
  (SELECT COUNT(*) FROM email_templates)          AS templates_seeded,
  (SELECT COUNT(*) FROM email_template_versions)  AS template_versions_seeded,
  (SELECT COUNT(*) FROM email_events)             AS events_seeded;
-- Expected: departments_seeded = 11, templates_seeded = 43,
-- template_versions_seeded = 43, events_seeded = 40.

-- Spot-check that no employee template carries restricted_data = 1.
SELECT COUNT(*) AS employee_restricted_violations
FROM email_templates
WHERE audience = 'employee' AND restricted_data = 1;
-- Expected: 0.

-- ---------------------------------------------------------------------------
-- Roll-back block (run only if you need to undo this seed).
-- The schema_phase31 / 32 rollbacks already drop the tables; this is the
-- targeted "undo seed but keep tables" path:
-- ---------------------------------------------------------------------------
-- DELETE FROM email_events;
-- DELETE FROM email_template_versions;
-- DELETE FROM email_templates;
-- DELETE FROM email_departments;
